// <auto-generated>
// Generated from packages/contracts/src by `pnpm contracts:emit`. Do not edit by hand.
// </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace Halcyonic.Contracts
{
    public static class ContractVersions
    {
        public const int EventSchema = 1;
        public const int CommandSchema = 1;
        public const int RealtimeProtocol = 1;
    }

    /// <summary>
    /// Serializer settings that match the wire contract. Timestamps stay strings, type metadata is
    /// ignored, and nulls are written explicitly. Tolerant reading ignores unknown properties;
    /// strict reading, for tests, rejects them.
    /// </summary>
    public static class HalcyonicJson
    {
        public static readonly JsonSerializerSettings Tolerant = CreateSettings(strict: false);
        public static readonly JsonSerializerSettings Strict = CreateSettings(strict: true);

        public static JsonSerializerSettings CreateSettings(bool strict) => new JsonSerializerSettings
        {
            DateParseHandling = DateParseHandling.None,
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            MissingMemberHandling = strict ? MissingMemberHandling.Error : MissingMemberHandling.Ignore,
            NullValueHandling = NullValueHandling.Include,
            ObjectCreationHandling = ObjectCreationHandling.Replace,
            TypeNameHandling = TypeNameHandling.None,
        };

        public static T Deserialize<T>(string json, bool strict = false) where T : class =>
            JsonConvert.DeserializeObject<T>(json, strict ? Strict : Tolerant)
            ?? throw new JsonSerializationException("Expected " + typeof(T).Name + " but the JSON is null.");

        public static string Serialize(object value) => JsonConvert.SerializeObject(value, Formatting.None, Tolerant);

        /// <summary>The wire form of an instant: UTC with exactly three fractional digits.</summary>
        public static string FormatTimestamp(DateTimeOffset instant) =>
            instant.UtcDateTime.ToString("yyyy-MM-dd'T'HH:mm:ss.fff'Z'", CultureInfo.InvariantCulture);
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum JournalOrigin
    {
        [EnumMember(Value = "live")] Live,
        [EnumMember(Value = "fixture")] Fixture,
    }

    public sealed class JournalInfo
    {
        [JsonProperty("journal_id", Required = Required.Always)]
        public string JournalId { get; set; } = default!;

        [JsonProperty("origin", Required = Required.Always)]
        public JournalOrigin Origin { get; set; }
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum CommandType
    {
        [EnumMember(Value = "project.create")] ProjectCreate,
        [EnumMember(Value = "workstream.create")] WorkstreamCreate,
        [EnumMember(Value = "execution.start")] ExecutionStart,
        [EnumMember(Value = "execution.send_instruction")] ExecutionSendInstruction,
        [EnumMember(Value = "execution.respond_to_approval")] ExecutionRespondToApproval,
        [EnumMember(Value = "execution.interrupt")] ExecutionInterrupt,
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum PolicyCategory
    {
        [EnumMember(Value = "low_consequence")] LowConsequence,
        [EnumMember(Value = "review_required")] ReviewRequired,
        [EnumMember(Value = "high_consequence")] HighConsequence,
    }

    public sealed class CommandPolicy
    {
        [JsonProperty("command_type", Required = Required.Always)]
        public CommandType CommandType { get; set; }

        [JsonProperty("policy", Required = Required.Always)]
        public PolicyCategory Policy { get; set; }
    }

    public sealed class ProjectView
    {
        [JsonProperty("project_id", Required = Required.Always)]
        public string ProjectId { get; set; } = default!;

        [JsonProperty("name", Required = Required.Always)]
        public string Name { get; set; } = default!;

        [JsonProperty("created_at", Required = Required.Always)]
        public string CreatedAt { get; set; } = default!;

        [JsonProperty("updated_at", Required = Required.Always)]
        public string UpdatedAt { get; set; } = default!;
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum WorkstreamStatus
    {
        [EnumMember(Value = "created")] Created,
        [EnumMember(Value = "starting")] Starting,
        [EnumMember(Value = "running")] Running,
        [EnumMember(Value = "verifying")] Verifying,
        [EnumMember(Value = "waiting_for_human")] WaitingForHuman,
        [EnumMember(Value = "completed")] Completed,
        [EnumMember(Value = "failed")] Failed,
        [EnumMember(Value = "interrupted")] Interrupted,
        [EnumMember(Value = "unknown")] Unknown,
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum AttentionLevel
    {
        [EnumMember(Value = "none")] None,
        [EnumMember(Value = "notice")] Notice,
        [EnumMember(Value = "action_required")] ActionRequired,
    }

    [JsonConverter(typeof(AttentionReasonConverter))]
    public abstract class AttentionReason
    {
        [JsonProperty("kind", Order = -2)]
        public string Kind => Discriminator;

        protected abstract string Discriminator { get; }

        [JsonProperty("execution_id", Required = Required.Always)]
        public string ExecutionId { get; set; } = default!;
    }

    public sealed class AttentionReasonConverter : JsonConverter
    {
        public override bool CanWrite => false;

        public override bool CanConvert(Type objectType) => typeof(AttentionReason).IsAssignableFrom(objectType);

        public override object? ReadJson(JsonReader reader, Type objectType, object? existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var item = JObject.Load(reader);
            var token = item["kind"];
            var tag = token != null && token.Type == JTokenType.String ? (string?)token : null;
            AttentionReason value = tag switch
            {
                "approval_pending" => new ApprovalPendingReason(),
                "execution_failed" => new ExecutionFailedReason(),
                "execution_state_unknown" => new ExecutionStateUnknownReason(),
                "verification_failed" => new VerificationFailedReason(),
                _ => throw new JsonSerializationException(tag == null
                    ? "AttentionReason has no string kind."
                    : "Unknown kind \"" + tag + "\" for AttentionReason."),
            };
            if (!objectType.IsInstanceOfType(value))
            {
                throw new JsonSerializationException(
                    "Expected " + objectType.Name + " but kind is \"" + tag + "\".");
            }
            using (var itemReader = item.CreateReader())
            {
                serializer.Populate(itemReader, value);
            }
            return value;
        }

        public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer) =>
            throw new NotSupportedException("Variants serialize as themselves.");
    }

    public sealed class ApprovalPendingReason : AttentionReason
    {
        protected override string Discriminator => "approval_pending";

        [JsonProperty("approval_id", Required = Required.Always)]
        public string ApprovalId { get; set; } = default!;
    }

    public sealed class ExecutionFailedReason : AttentionReason
    {
        protected override string Discriminator => "execution_failed";
    }

    public sealed class ExecutionStateUnknownReason : AttentionReason
    {
        protected override string Discriminator => "execution_state_unknown";
    }

    public sealed class VerificationFailedReason : AttentionReason
    {
        protected override string Discriminator => "verification_failed";

        [JsonProperty("test_run_id", Required = Required.Always)]
        public string TestRunId { get; set; } = default!;
    }

    public sealed class Attention
    {
        [JsonProperty("level", Required = Required.Always)]
        public AttentionLevel Level { get; set; }

        [JsonProperty("reasons", Required = Required.Always)]
        public List<AttentionReason> Reasons { get; set; } = new List<AttentionReason>();
    }

    public sealed class WorkstreamView
    {
        [JsonProperty("workstream_id", Required = Required.Always)]
        public string WorkstreamId { get; set; } = default!;

        [JsonProperty("project_id", Required = Required.Always)]
        public string ProjectId { get; set; } = default!;

        [JsonProperty("title", Required = Required.Always)]
        public string Title { get; set; } = default!;

        [JsonProperty("objective", Required = Required.AllowNull)]
        public string? Objective { get; set; }

        [JsonProperty("status", Required = Required.Always)]
        public WorkstreamStatus Status { get; set; }

        [JsonProperty("attention", Required = Required.Always)]
        public Attention Attention { get; set; } = default!;

        [JsonProperty("current_execution_id", Required = Required.AllowNull)]
        public string? CurrentExecutionId { get; set; }

        [JsonProperty("execution_ids", Required = Required.Always)]
        public List<string> ExecutionIds { get; set; } = new List<string>();

        [JsonProperty("created_at", Required = Required.Always)]
        public string CreatedAt { get; set; } = default!;

        [JsonProperty("updated_at", Required = Required.Always)]
        public string UpdatedAt { get; set; } = default!;
    }

    public sealed class RuntimeRef
    {
        [JsonProperty("runtime_id", Required = Required.Always)]
        public string RuntimeId { get; set; } = default!;

        [JsonProperty("kind", Required = Required.Always)]
        public string Kind { get; set; } = default!;

        [JsonProperty("display_name", Required = Required.Always)]
        public string DisplayName { get; set; } = default!;

        [JsonProperty("synthetic", Required = Required.Always)]
        public bool Synthetic { get; set; }
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ExecutionStatus
    {
        [EnumMember(Value = "starting")] Starting,
        [EnumMember(Value = "running")] Running,
        [EnumMember(Value = "verifying")] Verifying,
        [EnumMember(Value = "waiting_for_human")] WaitingForHuman,
        [EnumMember(Value = "completed")] Completed,
        [EnumMember(Value = "failed")] Failed,
        [EnumMember(Value = "interrupted")] Interrupted,
        [EnumMember(Value = "unknown")] Unknown,
    }

    public sealed class ErrorInfo
    {
        [JsonProperty("code", Required = Required.Always)]
        public string Code { get; set; } = default!;

        [JsonProperty("message", Required = Required.Always)]
        public string Message { get; set; } = default!;
    }

    [JsonConverter(typeof(ApprovalSubjectConverter))]
    public abstract class ApprovalSubject
    {
        [JsonProperty("kind", Order = -2)]
        public string Kind => Discriminator;

        protected abstract string Discriminator { get; }
    }

    public sealed class ApprovalSubjectConverter : JsonConverter
    {
        public override bool CanWrite => false;

        public override bool CanConvert(Type objectType) => typeof(ApprovalSubject).IsAssignableFrom(objectType);

        public override object? ReadJson(JsonReader reader, Type objectType, object? existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var item = JObject.Load(reader);
            var token = item["kind"];
            var tag = token != null && token.Type == JTokenType.String ? (string?)token : null;
            ApprovalSubject value = tag switch
            {
                "tool_use" => new ToolUseSubject(),
                _ => throw new JsonSerializationException(tag == null
                    ? "ApprovalSubject has no string kind."
                    : "Unknown kind \"" + tag + "\" for ApprovalSubject."),
            };
            if (!objectType.IsInstanceOfType(value))
            {
                throw new JsonSerializationException(
                    "Expected " + objectType.Name + " but kind is \"" + tag + "\".");
            }
            using (var itemReader = item.CreateReader())
            {
                serializer.Populate(itemReader, value);
            }
            return value;
        }

        public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer) =>
            throw new NotSupportedException("Variants serialize as themselves.");
    }

    public sealed class ToolUseSubject : ApprovalSubject
    {
        protected override string Discriminator => "tool_use";

        [JsonProperty("tool_name", Required = Required.Always)]
        public string ToolName { get; set; } = default!;

        [JsonProperty("summary", Required = Required.Always)]
        public string Summary { get; set; } = default!;
    }

    public sealed class ApprovalView
    {
        [JsonProperty("approval_id", Required = Required.Always)]
        public string ApprovalId { get; set; } = default!;

        [JsonProperty("subject", Required = Required.Always)]
        public ApprovalSubject Subject { get; set; } = default!;

        [JsonProperty("requested_at", Required = Required.Always)]
        public string RequestedAt { get; set; } = default!;
    }

    public sealed class ToolActivityView
    {
        [JsonProperty("tool_call_id", Required = Required.Always)]
        public string ToolCallId { get; set; } = default!;

        [JsonProperty("tool_name", Required = Required.Always)]
        public string ToolName { get; set; } = default!;

        [JsonProperty("title", Required = Required.AllowNull)]
        public string? Title { get; set; }

        [JsonProperty("started_at", Required = Required.Always)]
        public string StartedAt { get; set; } = default!;
    }

    public sealed class TestRunView
    {
        [JsonProperty("test_run_id", Required = Required.Always)]
        public string TestRunId { get; set; } = default!;

        [JsonProperty("label", Required = Required.AllowNull)]
        public string? Label { get; set; }

        [JsonProperty("started_at", Required = Required.Always)]
        public string StartedAt { get; set; } = default!;
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum TestOutcome
    {
        [EnumMember(Value = "passed")] Passed,
        [EnumMember(Value = "failed")] Failed,
        [EnumMember(Value = "errored")] Errored,
    }

    public sealed class TestRunResultView
    {
        [JsonProperty("test_run_id", Required = Required.Always)]
        public string TestRunId { get; set; } = default!;

        [JsonProperty("label", Required = Required.AllowNull)]
        public string? Label { get; set; }

        [JsonProperty("outcome", Required = Required.Always)]
        public TestOutcome Outcome { get; set; }

        [JsonProperty("summary", Required = Required.AllowNull)]
        public string? Summary { get; set; }

        [JsonProperty("completed_at", Required = Required.Always)]
        public string CompletedAt { get; set; } = default!;
    }

    public sealed class ExecutionView
    {
        [JsonProperty("execution_id", Required = Required.Always)]
        public string ExecutionId { get; set; } = default!;

        [JsonProperty("workstream_id", Required = Required.Always)]
        public string WorkstreamId { get; set; } = default!;

        [JsonProperty("project_id", Required = Required.Always)]
        public string ProjectId { get; set; } = default!;

        [JsonProperty("runtime", Required = Required.Always)]
        public RuntimeRef Runtime { get; set; } = default!;

        [JsonProperty("native_id", Required = Required.AllowNull)]
        public string? NativeId { get; set; }

        [JsonProperty("instruction", Required = Required.Always)]
        public string Instruction { get; set; } = default!;

        [JsonProperty("status", Required = Required.Always)]
        public ExecutionStatus Status { get; set; }

        [JsonProperty("status_reason", Required = Required.AllowNull)]
        public ErrorInfo? StatusReason { get; set; }

        [JsonProperty("pending_approvals", Required = Required.Always)]
        public List<ApprovalView> PendingApprovals { get; set; } = new List<ApprovalView>();

        [JsonProperty("active_tools", Required = Required.Always)]
        public List<ToolActivityView> ActiveTools { get; set; } = new List<ToolActivityView>();

        [JsonProperty("active_test_run", Required = Required.AllowNull)]
        public TestRunView? ActiveTestRun { get; set; }

        [JsonProperty("last_test_run", Required = Required.AllowNull)]
        public TestRunResultView? LastTestRun { get; set; }

        [JsonProperty("turn_count", Required = Required.Always)]
        public long TurnCount { get; set; }

        [JsonProperty("created_at", Required = Required.Always)]
        public string CreatedAt { get; set; } = default!;

        [JsonProperty("started_at", Required = Required.AllowNull)]
        public string? StartedAt { get; set; }

        [JsonProperty("updated_at", Required = Required.Always)]
        public string UpdatedAt { get; set; } = default!;
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum CommandStatus
    {
        [EnumMember(Value = "accepted")] Accepted,
        [EnumMember(Value = "rejected")] Rejected,
        [EnumMember(Value = "completed")] Completed,
        [EnumMember(Value = "failed")] Failed,
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum RejectionCode
    {
        [EnumMember(Value = "project_not_found")] ProjectNotFound,
        [EnumMember(Value = "workstream_not_found")] WorkstreamNotFound,
        [EnumMember(Value = "execution_not_found")] ExecutionNotFound,
        [EnumMember(Value = "runtime_not_found")] RuntimeNotFound,
        [EnumMember(Value = "approval_not_found")] ApprovalNotFound,
        [EnumMember(Value = "capability_unsupported")] CapabilityUnsupported,
        [EnumMember(Value = "invalid_state")] InvalidState,
        [EnumMember(Value = "invalid_runtime_options")] InvalidRuntimeOptions,
    }

    public sealed class CommandRejection
    {
        [JsonProperty("code", Required = Required.Always)]
        public RejectionCode Code { get; set; }

        [JsonProperty("message", Required = Required.Always)]
        public string Message { get; set; } = default!;
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum FailureEffect
    {
        [EnumMember(Value = "none")] None,
        [EnumMember(Value = "unknown")] Unknown,
    }

    public sealed class CommandFailure
    {
        [JsonProperty("code", Required = Required.Always)]
        public string Code { get; set; } = default!;

        [JsonProperty("message", Required = Required.Always)]
        public string Message { get; set; } = default!;

        [JsonProperty("effect", Required = Required.Always)]
        public FailureEffect Effect { get; set; }
    }

    [JsonConverter(typeof(CommandResultConverter))]
    public abstract class CommandResult
    {
        [JsonProperty("kind", Order = -2)]
        public string Kind => Discriminator;

        protected abstract string Discriminator { get; }
    }

    public sealed class CommandResultConverter : JsonConverter
    {
        public override bool CanWrite => false;

        public override bool CanConvert(Type objectType) => typeof(CommandResult).IsAssignableFrom(objectType);

        public override object? ReadJson(JsonReader reader, Type objectType, object? existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var item = JObject.Load(reader);
            var token = item["kind"];
            var tag = token != null && token.Type == JTokenType.String ? (string?)token : null;
            CommandResult value = tag switch
            {
                "project_created" => new ProjectCreatedResult(),
                "workstream_created" => new WorkstreamCreatedResult(),
                "execution_created" => new ExecutionCreatedResult(),
                _ => throw new JsonSerializationException(tag == null
                    ? "CommandResult has no string kind."
                    : "Unknown kind \"" + tag + "\" for CommandResult."),
            };
            if (!objectType.IsInstanceOfType(value))
            {
                throw new JsonSerializationException(
                    "Expected " + objectType.Name + " but kind is \"" + tag + "\".");
            }
            using (var itemReader = item.CreateReader())
            {
                serializer.Populate(itemReader, value);
            }
            return value;
        }

        public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer) =>
            throw new NotSupportedException("Variants serialize as themselves.");
    }

    public sealed class ProjectCreatedResult : CommandResult
    {
        protected override string Discriminator => "project_created";

        [JsonProperty("project_id", Required = Required.Always)]
        public string ProjectId { get; set; } = default!;
    }

    public sealed class WorkstreamCreatedResult : CommandResult
    {
        protected override string Discriminator => "workstream_created";

        [JsonProperty("workstream_id", Required = Required.Always)]
        public string WorkstreamId { get; set; } = default!;
    }

    public sealed class ExecutionCreatedResult : CommandResult
    {
        protected override string Discriminator => "execution_created";

        [JsonProperty("execution_id", Required = Required.Always)]
        public string ExecutionId { get; set; } = default!;
    }

    public sealed class CommandView
    {
        [JsonProperty("command_id", Required = Required.Always)]
        public string CommandId { get; set; } = default!;

        [JsonProperty("command_type", Required = Required.Always)]
        public CommandType CommandType { get; set; }

        [JsonProperty("status", Required = Required.Always)]
        public CommandStatus Status { get; set; }

        [JsonProperty("project_id", Required = Required.AllowNull)]
        public string? ProjectId { get; set; }

        [JsonProperty("workstream_id", Required = Required.AllowNull)]
        public string? WorkstreamId { get; set; }

        [JsonProperty("execution_id", Required = Required.AllowNull)]
        public string? ExecutionId { get; set; }

        [JsonProperty("issued_at", Required = Required.Always)]
        public string IssuedAt { get; set; } = default!;

        [JsonProperty("updated_at", Required = Required.Always)]
        public string UpdatedAt { get; set; } = default!;

        [JsonProperty("rejection", Required = Required.AllowNull)]
        public CommandRejection? Rejection { get; set; }

        [JsonProperty("failure", Required = Required.AllowNull)]
        public CommandFailure? Failure { get; set; }

        [JsonProperty("result", Required = Required.AllowNull)]
        public CommandResult? Result { get; set; }
    }

    public sealed class RuntimeCapabilities
    {
        [JsonProperty("start_execution", Required = Required.Always)]
        public bool StartExecution { get; set; }

        [JsonProperty("instruct_at_rest", Required = Required.Always)]
        public bool InstructAtRest { get; set; }

        [JsonProperty("instruct_while_running", Required = Required.Always)]
        public bool InstructWhileRunning { get; set; }

        [JsonProperty("respond_to_approval", Required = Required.Always)]
        public bool RespondToApproval { get; set; }

        [JsonProperty("interrupt", Required = Required.Always)]
        public bool Interrupt { get; set; }
    }

    public sealed class RuntimeDescriptor
    {
        [JsonProperty("runtime_id", Required = Required.Always)]
        public string RuntimeId { get; set; } = default!;

        [JsonProperty("kind", Required = Required.Always)]
        public string Kind { get; set; } = default!;

        [JsonProperty("display_name", Required = Required.Always)]
        public string DisplayName { get; set; } = default!;

        [JsonProperty("synthetic", Required = Required.Always)]
        public bool Synthetic { get; set; }

        [JsonProperty("capabilities", Required = Required.Always)]
        public RuntimeCapabilities Capabilities { get; set; } = default!;
    }

    public sealed class Snapshot
    {
        [JsonProperty("journal", Required = Required.Always)]
        public JournalInfo Journal { get; set; } = default!;

        [JsonProperty("position", Required = Required.Always)]
        public long Position { get; set; }

        [JsonProperty("projects", Required = Required.Always)]
        public List<ProjectView> Projects { get; set; } = new List<ProjectView>();

        [JsonProperty("workstreams", Required = Required.Always)]
        public List<WorkstreamView> Workstreams { get; set; } = new List<WorkstreamView>();

        [JsonProperty("executions", Required = Required.Always)]
        public List<ExecutionView> Executions { get; set; } = new List<ExecutionView>();

        [JsonProperty("commands", Required = Required.Always)]
        public List<CommandView> Commands { get; set; } = new List<CommandView>();

        [JsonProperty("runtimes", Required = Required.Always)]
        public List<RuntimeDescriptor> Runtimes { get; set; } = new List<RuntimeDescriptor>();
    }

    [JsonConverter(typeof(ProvenanceConverter))]
    public abstract class Provenance
    {
        [JsonProperty("epistemic", Order = -2)]
        public string Epistemic => Discriminator;

        protected abstract string Discriminator { get; }

        [JsonProperty("native_type", Required = Required.AllowNull)]
        public string? NativeType { get; set; }
    }

    public sealed class ProvenanceConverter : JsonConverter
    {
        public override bool CanWrite => false;

        public override bool CanConvert(Type objectType) => typeof(Provenance).IsAssignableFrom(objectType);

        public override object? ReadJson(JsonReader reader, Type objectType, object? existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var item = JObject.Load(reader);
            var token = item["epistemic"];
            var tag = token != null && token.Type == JTokenType.String ? (string?)token : null;
            Provenance value = tag switch
            {
                "observed" => new ObservedProvenance(),
                "reported" => new ReportedProvenance(),
                "inferred" => new InferredProvenance(),
                _ => throw new JsonSerializationException(tag == null
                    ? "Provenance has no string epistemic."
                    : "Unknown epistemic \"" + tag + "\" for Provenance."),
            };
            if (!objectType.IsInstanceOfType(value))
            {
                throw new JsonSerializationException(
                    "Expected " + objectType.Name + " but epistemic is \"" + tag + "\".");
            }
            using (var itemReader = item.CreateReader())
            {
                serializer.Populate(itemReader, value);
            }
            return value;
        }

        public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer) =>
            throw new NotSupportedException("Variants serialize as themselves.");
    }

    public sealed class ObservedProvenance : Provenance
    {
        protected override string Discriminator => "observed";
    }

    public sealed class ReportedProvenance : Provenance
    {
        protected override string Discriminator => "reported";
    }

    public sealed class InferredProvenance : Provenance
    {
        protected override string Discriminator => "inferred";

        [JsonProperty("rule", Required = Required.Always)]
        public string Rule { get; set; } = default!;
    }

    [JsonConverter(typeof(EventSourceConverter))]
    public abstract class EventSource
    {
        [JsonProperty("kind", Order = -2)]
        public string Kind => Discriminator;

        protected abstract string Discriminator { get; }
    }

    public sealed class EventSourceConverter : JsonConverter
    {
        public override bool CanWrite => false;

        public override bool CanConvert(Type objectType) => typeof(EventSource).IsAssignableFrom(objectType);

        public override object? ReadJson(JsonReader reader, Type objectType, object? existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var item = JObject.Load(reader);
            var token = item["kind"];
            var tag = token != null && token.Type == JTokenType.String ? (string?)token : null;
            EventSource value = tag switch
            {
                "control_plane" => new ControlPlaneSource(),
                "runtime" => new RuntimeSource(),
                _ => throw new JsonSerializationException(tag == null
                    ? "EventSource has no string kind."
                    : "Unknown kind \"" + tag + "\" for EventSource."),
            };
            if (!objectType.IsInstanceOfType(value))
            {
                throw new JsonSerializationException(
                    "Expected " + objectType.Name + " but kind is \"" + tag + "\".");
            }
            using (var itemReader = item.CreateReader())
            {
                serializer.Populate(itemReader, value);
            }
            return value;
        }

        public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer) =>
            throw new NotSupportedException("Variants serialize as themselves.");
    }

    public sealed class ControlPlaneSource : EventSource
    {
        protected override string Discriminator => "control_plane";
    }

    public sealed class RuntimeSource : EventSource
    {
        protected override string Discriminator => "runtime";

        [JsonProperty("runtime_id", Required = Required.Always)]
        public string RuntimeId { get; set; } = default!;
    }

    public sealed class ProjectCreatedPayload
    {
        [JsonProperty("name", Required = Required.Always)]
        public string Name { get; set; } = default!;
    }

    public sealed class WorkstreamCreatedPayload
    {
        [JsonProperty("title", Required = Required.Always)]
        public string Title { get; set; } = default!;

        [JsonProperty("objective", Required = Required.AllowNull)]
        public string? Objective { get; set; }
    }

    public sealed class ExecutionCreatedPayload
    {
        [JsonProperty("runtime", Required = Required.Always)]
        public RuntimeRef Runtime { get; set; } = default!;

        [JsonProperty("instruction", Required = Required.Always)]
        public string Instruction { get; set; } = default!;
    }

    public sealed class ExecutionStartFailedPayload
    {
        [JsonProperty("error", Required = Required.Always)]
        public ErrorInfo Error { get; set; } = default!;
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum StateUnknownCode
    {
        [EnumMember(Value = "control_plane_restarted")] ControlPlaneRestarted,
        [EnumMember(Value = "start_outcome_unknown")] StartOutcomeUnknown,
    }

    public sealed class ExecutionStateUnknownPayload
    {
        [JsonProperty("code", Required = Required.Always)]
        public StateUnknownCode Code { get; set; }

        [JsonProperty("message", Required = Required.Always)]
        public string Message { get; set; } = default!;
    }

    public sealed class ClientInfo
    {
        [JsonProperty("name", Required = Required.Always)]
        public string Name { get; set; } = default!;

        [JsonProperty("version", Required = Required.AllowNull)]
        public string? Version { get; set; }

        [JsonProperty("device_label", Required = Required.AllowNull)]
        public string? DeviceLabel { get; set; }
    }

    public sealed class ProjectCreatePayload
    {
        [JsonProperty("name", Required = Required.Always)]
        public string Name { get; set; } = default!;
    }

    public sealed class WorkstreamCreatePayload
    {
        [JsonProperty("project_id", Required = Required.Always)]
        public string ProjectId { get; set; } = default!;

        [JsonProperty("title", Required = Required.Always)]
        public string Title { get; set; } = default!;

        [JsonProperty("objective", Required = Required.AllowNull)]
        public string? Objective { get; set; }
    }

    public sealed class ExecutionStartPayload
    {
        [JsonProperty("workstream_id", Required = Required.Always)]
        public string WorkstreamId { get; set; } = default!;

        [JsonProperty("runtime_id", Required = Required.Always)]
        public string RuntimeId { get; set; } = default!;

        [JsonProperty("instruction", Required = Required.Always)]
        public string Instruction { get; set; } = default!;

        [JsonProperty("options", Required = Required.Always)]
        public Dictionary<string, JToken> Options { get; set; } = new Dictionary<string, JToken>();
    }

    public sealed class ExecutionSendInstructionPayload
    {
        [JsonProperty("execution_id", Required = Required.Always)]
        public string ExecutionId { get; set; } = default!;

        [JsonProperty("text", Required = Required.Always)]
        public string Text { get; set; } = default!;
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ApprovalDecision
    {
        [EnumMember(Value = "approve")] Approve,
        [EnumMember(Value = "deny")] Deny,
    }

    public sealed class ExecutionRespondToApprovalPayload
    {
        [JsonProperty("execution_id", Required = Required.Always)]
        public string ExecutionId { get; set; } = default!;

        [JsonProperty("approval_id", Required = Required.Always)]
        public string ApprovalId { get; set; } = default!;

        [JsonProperty("decision", Required = Required.Always)]
        public ApprovalDecision Decision { get; set; }

        [JsonProperty("message", Required = Required.AllowNull)]
        public string? Message { get; set; }
    }

    public sealed class ExecutionInterruptPayload
    {
        [JsonProperty("execution_id", Required = Required.Always)]
        public string ExecutionId { get; set; } = default!;
    }

    [JsonConverter(typeof(CommandEnvelopeConverter))]
    public abstract class CommandEnvelope
    {
        [JsonProperty("command_type", Order = -2)]
        public string CommandType => Discriminator;

        protected abstract string Discriminator { get; }

        [JsonProperty("schema_version", Required = Required.Always)]
        public long SchemaVersion { get; set; } = 1;

        [JsonProperty("command_id", Required = Required.Always)]
        public string CommandId { get; set; } = default!;

        [JsonProperty("issued_at", Required = Required.Always)]
        public string IssuedAt { get; set; } = default!;

        [JsonProperty("client", Required = Required.Always)]
        public ClientInfo Client { get; set; } = default!;
    }

    public sealed class CommandEnvelopeConverter : JsonConverter
    {
        public override bool CanWrite => false;

        public override bool CanConvert(Type objectType) => typeof(CommandEnvelope).IsAssignableFrom(objectType);

        public override object? ReadJson(JsonReader reader, Type objectType, object? existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var item = JObject.Load(reader);
            var token = item["command_type"];
            var tag = token != null && token.Type == JTokenType.String ? (string?)token : null;
            CommandEnvelope value = tag switch
            {
                "project.create" => new ProjectCreateCommand(),
                "workstream.create" => new WorkstreamCreateCommand(),
                "execution.start" => new ExecutionStartCommand(),
                "execution.send_instruction" => new ExecutionSendInstructionCommand(),
                "execution.respond_to_approval" => new ExecutionRespondToApprovalCommand(),
                "execution.interrupt" => new ExecutionInterruptCommand(),
                _ => throw new JsonSerializationException(tag == null
                    ? "CommandEnvelope has no string command_type."
                    : "Unknown command_type \"" + tag + "\" for CommandEnvelope."),
            };
            if (!objectType.IsInstanceOfType(value))
            {
                throw new JsonSerializationException(
                    "Expected " + objectType.Name + " but command_type is \"" + tag + "\".");
            }
            using (var itemReader = item.CreateReader())
            {
                serializer.Populate(itemReader, value);
            }
            return value;
        }

        public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer) =>
            throw new NotSupportedException("Variants serialize as themselves.");
    }

    public sealed class ProjectCreateCommand : CommandEnvelope
    {
        protected override string Discriminator => "project.create";

        [JsonProperty("payload", Required = Required.Always)]
        public ProjectCreatePayload Payload { get; set; } = default!;
    }

    public sealed class WorkstreamCreateCommand : CommandEnvelope
    {
        protected override string Discriminator => "workstream.create";

        [JsonProperty("payload", Required = Required.Always)]
        public WorkstreamCreatePayload Payload { get; set; } = default!;
    }

    public sealed class ExecutionStartCommand : CommandEnvelope
    {
        protected override string Discriminator => "execution.start";

        [JsonProperty("payload", Required = Required.Always)]
        public ExecutionStartPayload Payload { get; set; } = default!;
    }

    public sealed class ExecutionSendInstructionCommand : CommandEnvelope
    {
        protected override string Discriminator => "execution.send_instruction";

        [JsonProperty("payload", Required = Required.Always)]
        public ExecutionSendInstructionPayload Payload { get; set; } = default!;
    }

    public sealed class ExecutionRespondToApprovalCommand : CommandEnvelope
    {
        protected override string Discriminator => "execution.respond_to_approval";

        [JsonProperty("payload", Required = Required.Always)]
        public ExecutionRespondToApprovalPayload Payload { get; set; } = default!;
    }

    public sealed class ExecutionInterruptCommand : CommandEnvelope
    {
        protected override string Discriminator => "execution.interrupt";

        [JsonProperty("payload", Required = Required.Always)]
        public ExecutionInterruptPayload Payload { get; set; } = default!;
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ReceivedVia
    {
        [EnumMember(Value = "http")] Http,
        [EnumMember(Value = "websocket")] Websocket,
        [EnumMember(Value = "internal")] Internal,
    }

    public sealed class CommandAcceptedPayload
    {
        [JsonProperty("command", Required = Required.Always)]
        public CommandEnvelope Command { get; set; } = default!;

        [JsonProperty("policy", Required = Required.Always)]
        public PolicyCategory Policy { get; set; }

        [JsonProperty("received_via", Required = Required.Always)]
        public ReceivedVia ReceivedVia { get; set; }
    }

    public sealed class CommandRejectedPayload
    {
        [JsonProperty("command", Required = Required.Always)]
        public CommandEnvelope Command { get; set; } = default!;

        [JsonProperty("rejection", Required = Required.Always)]
        public CommandRejection Rejection { get; set; } = default!;

        [JsonProperty("received_via", Required = Required.Always)]
        public ReceivedVia ReceivedVia { get; set; }
    }

    public sealed class CommandCompletedPayload
    {
        [JsonProperty("command_id", Required = Required.Always)]
        public string CommandId { get; set; } = default!;

        [JsonProperty("command_type", Required = Required.Always)]
        public CommandType CommandType { get; set; }

        [JsonProperty("result", Required = Required.AllowNull)]
        public CommandResult? Result { get; set; }
    }

    public sealed class CommandFailedPayload
    {
        [JsonProperty("command_id", Required = Required.Always)]
        public string CommandId { get; set; } = default!;

        [JsonProperty("command_type", Required = Required.Always)]
        public CommandType CommandType { get; set; }

        [JsonProperty("failure", Required = Required.Always)]
        public CommandFailure Failure { get; set; } = default!;
    }

    public sealed class RuntimeExecutionStartedPayload
    {
        [JsonProperty("native_id", Required = Required.AllowNull)]
        public string? NativeId { get; set; }
    }

    public sealed class RuntimeTurnStartedPayload
    {
        [JsonProperty("turn_id", Required = Required.AllowNull)]
        public string? TurnId { get; set; }
    }

    public sealed class RuntimeTurnCompletedPayload
    {
        [JsonProperty("turn_id", Required = Required.AllowNull)]
        public string? TurnId { get; set; }
    }

    public sealed class RuntimeTurnFailedPayload
    {
        [JsonProperty("turn_id", Required = Required.AllowNull)]
        public string? TurnId { get; set; }

        [JsonProperty("error", Required = Required.Always)]
        public ErrorInfo Error { get; set; } = default!;
    }

    public sealed class RuntimeTurnInterruptedPayload
    {
        [JsonProperty("turn_id", Required = Required.AllowNull)]
        public string? TurnId { get; set; }
    }

    public sealed class RuntimeApprovalRequestedPayload
    {
        [JsonProperty("approval_id", Required = Required.Always)]
        public string ApprovalId { get; set; } = default!;

        [JsonProperty("subject", Required = Required.Always)]
        public ApprovalSubject Subject { get; set; } = default!;
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ApprovalResolution
    {
        [EnumMember(Value = "approved")] Approved,
        [EnumMember(Value = "denied")] Denied,
    }

    public sealed class RuntimeApprovalResolvedPayload
    {
        [JsonProperty("approval_id", Required = Required.Always)]
        public string ApprovalId { get; set; } = default!;

        [JsonProperty("decision", Required = Required.Always)]
        public ApprovalResolution Decision { get; set; }
    }

    public sealed class RuntimeToolStartedPayload
    {
        [JsonProperty("tool_call_id", Required = Required.Always)]
        public string ToolCallId { get; set; } = default!;

        [JsonProperty("tool_name", Required = Required.Always)]
        public string ToolName { get; set; } = default!;

        [JsonProperty("title", Required = Required.AllowNull)]
        public string? Title { get; set; }
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ToolOutcome
    {
        [EnumMember(Value = "succeeded")] Succeeded,
        [EnumMember(Value = "failed")] Failed,
    }

    public sealed class RuntimeToolCompletedPayload
    {
        [JsonProperty("tool_call_id", Required = Required.Always)]
        public string ToolCallId { get; set; } = default!;

        [JsonProperty("outcome", Required = Required.Always)]
        public ToolOutcome Outcome { get; set; }
    }

    public sealed class RuntimeAgentMessagePayload
    {
        [JsonProperty("text", Required = Required.Always)]
        public string Text { get; set; } = default!;
    }

    public sealed class RuntimeTestRunStartedPayload
    {
        [JsonProperty("test_run_id", Required = Required.Always)]
        public string TestRunId { get; set; } = default!;

        [JsonProperty("label", Required = Required.AllowNull)]
        public string? Label { get; set; }
    }

    public sealed class RuntimeTestRunCompletedPayload
    {
        [JsonProperty("test_run_id", Required = Required.Always)]
        public string TestRunId { get; set; } = default!;

        [JsonProperty("outcome", Required = Required.Always)]
        public TestOutcome Outcome { get; set; }

        [JsonProperty("summary", Required = Required.AllowNull)]
        public string? Summary { get; set; }
    }

    public sealed class RuntimeConnectionLostPayload
    {
        [JsonProperty("reason", Required = Required.Always)]
        public string Reason { get; set; } = default!;
    }

    [JsonConverter(typeof(EventEnvelopeConverter))]
    public abstract class EventEnvelope
    {
        [JsonProperty("event_type", Order = -2)]
        public string EventType => Discriminator;

        protected abstract string Discriminator { get; }

        [JsonProperty("schema_version", Required = Required.Always)]
        public long SchemaVersion { get; set; } = 1;

        [JsonProperty("event_id", Required = Required.Always)]
        public string EventId { get; set; } = default!;

        [JsonProperty("source_native_id", Required = Required.AllowNull)]
        public string? SourceNativeId { get; set; }

        [JsonProperty("sequence", Required = Required.AllowNull)]
        public long? Sequence { get; set; }

        [JsonProperty("occurred_at", Required = Required.Always)]
        public string OccurredAt { get; set; } = default!;

        [JsonProperty("ingested_at", Required = Required.Always)]
        public string IngestedAt { get; set; } = default!;

        [JsonProperty("correlation_id", Required = Required.AllowNull)]
        public string? CorrelationId { get; set; }

        [JsonProperty("causation_id", Required = Required.AllowNull)]
        public string? CausationId { get; set; }

        [JsonProperty("provenance", Required = Required.Always)]
        public Provenance Provenance { get; set; } = default!;

        [JsonProperty("project_id", Required = Required.AllowNull)]
        public string? ProjectId { get; set; }

        [JsonProperty("workstream_id", Required = Required.AllowNull)]
        public string? WorkstreamId { get; set; }

        [JsonProperty("execution_id", Required = Required.AllowNull)]
        public string? ExecutionId { get; set; }

        [JsonProperty("source", Required = Required.Always)]
        public EventSource Source { get; set; } = default!;
    }

    public sealed class EventEnvelopeConverter : JsonConverter
    {
        public override bool CanWrite => false;

        public override bool CanConvert(Type objectType) => typeof(EventEnvelope).IsAssignableFrom(objectType);

        public override object? ReadJson(JsonReader reader, Type objectType, object? existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var item = JObject.Load(reader);
            var token = item["event_type"];
            var tag = token != null && token.Type == JTokenType.String ? (string?)token : null;
            EventEnvelope value = tag switch
            {
                "project.created" => new ProjectCreatedEvent(),
                "workstream.created" => new WorkstreamCreatedEvent(),
                "execution.created" => new ExecutionCreatedEvent(),
                "execution.start_failed" => new ExecutionStartFailedEvent(),
                "execution.state_unknown" => new ExecutionStateUnknownEvent(),
                "command.accepted" => new CommandAcceptedEvent(),
                "command.rejected" => new CommandRejectedEvent(),
                "command.completed" => new CommandCompletedEvent(),
                "command.failed" => new CommandFailedEvent(),
                "runtime.execution.started" => new RuntimeExecutionStartedEvent(),
                "runtime.turn.started" => new RuntimeTurnStartedEvent(),
                "runtime.turn.completed" => new RuntimeTurnCompletedEvent(),
                "runtime.turn.failed" => new RuntimeTurnFailedEvent(),
                "runtime.turn.interrupted" => new RuntimeTurnInterruptedEvent(),
                "runtime.approval.requested" => new RuntimeApprovalRequestedEvent(),
                "runtime.approval.resolved" => new RuntimeApprovalResolvedEvent(),
                "runtime.tool.started" => new RuntimeToolStartedEvent(),
                "runtime.tool.completed" => new RuntimeToolCompletedEvent(),
                "runtime.agent_message" => new RuntimeAgentMessageEvent(),
                "runtime.test_run.started" => new RuntimeTestRunStartedEvent(),
                "runtime.test_run.completed" => new RuntimeTestRunCompletedEvent(),
                "runtime.connection.lost" => new RuntimeConnectionLostEvent(),
                _ => throw new JsonSerializationException(tag == null
                    ? "EventEnvelope has no string event_type."
                    : "Unknown event_type \"" + tag + "\" for EventEnvelope."),
            };
            if (!objectType.IsInstanceOfType(value))
            {
                throw new JsonSerializationException(
                    "Expected " + objectType.Name + " but event_type is \"" + tag + "\".");
            }
            using (var itemReader = item.CreateReader())
            {
                serializer.Populate(itemReader, value);
            }
            return value;
        }

        public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer) =>
            throw new NotSupportedException("Variants serialize as themselves.");
    }

    public sealed class ProjectCreatedEvent : EventEnvelope
    {
        protected override string Discriminator => "project.created";

        [JsonProperty("payload", Required = Required.Always)]
        public ProjectCreatedPayload Payload { get; set; } = default!;
    }

    public sealed class WorkstreamCreatedEvent : EventEnvelope
    {
        protected override string Discriminator => "workstream.created";

        [JsonProperty("payload", Required = Required.Always)]
        public WorkstreamCreatedPayload Payload { get; set; } = default!;
    }

    public sealed class ExecutionCreatedEvent : EventEnvelope
    {
        protected override string Discriminator => "execution.created";

        [JsonProperty("payload", Required = Required.Always)]
        public ExecutionCreatedPayload Payload { get; set; } = default!;
    }

    public sealed class ExecutionStartFailedEvent : EventEnvelope
    {
        protected override string Discriminator => "execution.start_failed";

        [JsonProperty("payload", Required = Required.Always)]
        public ExecutionStartFailedPayload Payload { get; set; } = default!;
    }

    public sealed class ExecutionStateUnknownEvent : EventEnvelope
    {
        protected override string Discriminator => "execution.state_unknown";

        [JsonProperty("payload", Required = Required.Always)]
        public ExecutionStateUnknownPayload Payload { get; set; } = default!;
    }

    public sealed class CommandAcceptedEvent : EventEnvelope
    {
        protected override string Discriminator => "command.accepted";

        [JsonProperty("payload", Required = Required.Always)]
        public CommandAcceptedPayload Payload { get; set; } = default!;
    }

    public sealed class CommandRejectedEvent : EventEnvelope
    {
        protected override string Discriminator => "command.rejected";

        [JsonProperty("payload", Required = Required.Always)]
        public CommandRejectedPayload Payload { get; set; } = default!;
    }

    public sealed class CommandCompletedEvent : EventEnvelope
    {
        protected override string Discriminator => "command.completed";

        [JsonProperty("payload", Required = Required.Always)]
        public CommandCompletedPayload Payload { get; set; } = default!;
    }

    public sealed class CommandFailedEvent : EventEnvelope
    {
        protected override string Discriminator => "command.failed";

        [JsonProperty("payload", Required = Required.Always)]
        public CommandFailedPayload Payload { get; set; } = default!;
    }

    public sealed class RuntimeExecutionStartedEvent : EventEnvelope
    {
        protected override string Discriminator => "runtime.execution.started";

        [JsonProperty("payload", Required = Required.Always)]
        public RuntimeExecutionStartedPayload Payload { get; set; } = default!;
    }

    public sealed class RuntimeTurnStartedEvent : EventEnvelope
    {
        protected override string Discriminator => "runtime.turn.started";

        [JsonProperty("payload", Required = Required.Always)]
        public RuntimeTurnStartedPayload Payload { get; set; } = default!;
    }

    public sealed class RuntimeTurnCompletedEvent : EventEnvelope
    {
        protected override string Discriminator => "runtime.turn.completed";

        [JsonProperty("payload", Required = Required.Always)]
        public RuntimeTurnCompletedPayload Payload { get; set; } = default!;
    }

    public sealed class RuntimeTurnFailedEvent : EventEnvelope
    {
        protected override string Discriminator => "runtime.turn.failed";

        [JsonProperty("payload", Required = Required.Always)]
        public RuntimeTurnFailedPayload Payload { get; set; } = default!;
    }

    public sealed class RuntimeTurnInterruptedEvent : EventEnvelope
    {
        protected override string Discriminator => "runtime.turn.interrupted";

        [JsonProperty("payload", Required = Required.Always)]
        public RuntimeTurnInterruptedPayload Payload { get; set; } = default!;
    }

    public sealed class RuntimeApprovalRequestedEvent : EventEnvelope
    {
        protected override string Discriminator => "runtime.approval.requested";

        [JsonProperty("payload", Required = Required.Always)]
        public RuntimeApprovalRequestedPayload Payload { get; set; } = default!;
    }

    public sealed class RuntimeApprovalResolvedEvent : EventEnvelope
    {
        protected override string Discriminator => "runtime.approval.resolved";

        [JsonProperty("payload", Required = Required.Always)]
        public RuntimeApprovalResolvedPayload Payload { get; set; } = default!;
    }

    public sealed class RuntimeToolStartedEvent : EventEnvelope
    {
        protected override string Discriminator => "runtime.tool.started";

        [JsonProperty("payload", Required = Required.Always)]
        public RuntimeToolStartedPayload Payload { get; set; } = default!;
    }

    public sealed class RuntimeToolCompletedEvent : EventEnvelope
    {
        protected override string Discriminator => "runtime.tool.completed";

        [JsonProperty("payload", Required = Required.Always)]
        public RuntimeToolCompletedPayload Payload { get; set; } = default!;
    }

    public sealed class RuntimeAgentMessageEvent : EventEnvelope
    {
        protected override string Discriminator => "runtime.agent_message";

        [JsonProperty("payload", Required = Required.Always)]
        public RuntimeAgentMessagePayload Payload { get; set; } = default!;
    }

    public sealed class RuntimeTestRunStartedEvent : EventEnvelope
    {
        protected override string Discriminator => "runtime.test_run.started";

        [JsonProperty("payload", Required = Required.Always)]
        public RuntimeTestRunStartedPayload Payload { get; set; } = default!;
    }

    public sealed class RuntimeTestRunCompletedEvent : EventEnvelope
    {
        protected override string Discriminator => "runtime.test_run.completed";

        [JsonProperty("payload", Required = Required.Always)]
        public RuntimeTestRunCompletedPayload Payload { get; set; } = default!;
    }

    public sealed class RuntimeConnectionLostEvent : EventEnvelope
    {
        protected override string Discriminator => "runtime.connection.lost";

        [JsonProperty("payload", Required = Required.Always)]
        public RuntimeConnectionLostPayload Payload { get; set; } = default!;
    }

    public sealed class EntityChanges
    {
        [JsonProperty("projects", Required = Required.Always)]
        public List<ProjectView> Projects { get; set; } = new List<ProjectView>();

        [JsonProperty("workstreams", Required = Required.Always)]
        public List<WorkstreamView> Workstreams { get; set; } = new List<WorkstreamView>();

        [JsonProperty("executions", Required = Required.Always)]
        public List<ExecutionView> Executions { get; set; } = new List<ExecutionView>();

        [JsonProperty("commands", Required = Required.Always)]
        public List<CommandView> Commands { get; set; } = new List<CommandView>();
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum CommandAckDisposition
    {
        [EnumMember(Value = "accepted")] Accepted,
        [EnumMember(Value = "rejected")] Rejected,
        [EnumMember(Value = "duplicate")] Duplicate,
        [EnumMember(Value = "conflict")] Conflict,
    }

    public sealed class ValidationIssue
    {
        [JsonProperty("path", Required = Required.Always)]
        public string Path { get; set; } = default!;

        [JsonProperty("message", Required = Required.Always)]
        public string Message { get; set; } = default!;
    }

    public sealed class ErrorBody
    {
        [JsonProperty("code", Required = Required.Always)]
        public string Code { get; set; } = default!;

        [JsonProperty("message", Required = Required.Always)]
        public string Message { get; set; } = default!;

        [JsonProperty("issues", Required = Required.Always)]
        public List<ValidationIssue> Issues { get; set; } = new List<ValidationIssue>();
    }

    [JsonConverter(typeof(ServerMessageConverter))]
    public abstract class ServerMessage
    {
        [JsonProperty("type", Order = -2)]
        public string Type => Discriminator;

        protected abstract string Discriminator { get; }
    }

    public sealed class ServerMessageConverter : JsonConverter
    {
        public override bool CanWrite => false;

        public override bool CanConvert(Type objectType) => typeof(ServerMessage).IsAssignableFrom(objectType);

        public override object? ReadJson(JsonReader reader, Type objectType, object? existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var item = JObject.Load(reader);
            var token = item["type"];
            var tag = token != null && token.Type == JTokenType.String ? (string?)token : null;
            ServerMessage value = tag switch
            {
                "welcome" => new WelcomeMessage(),
                "snapshot" => new SnapshotMessage(),
                "event" => new EventMessage(),
                "command_ack" => new CommandAckMessage(),
                "pong" => new PongMessage(),
                "error" => new ErrorMessage(),
                _ => throw new JsonSerializationException(tag == null
                    ? "ServerMessage has no string type."
                    : "Unknown type \"" + tag + "\" for ServerMessage."),
            };
            if (!objectType.IsInstanceOfType(value))
            {
                throw new JsonSerializationException(
                    "Expected " + objectType.Name + " but type is \"" + tag + "\".");
            }
            using (var itemReader = item.CreateReader())
            {
                serializer.Populate(itemReader, value);
            }
            return value;
        }

        public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer) =>
            throw new NotSupportedException("Variants serialize as themselves.");
    }

    public sealed class WelcomeMessage : ServerMessage
    {
        protected override string Discriminator => "welcome";

        [JsonProperty("protocol", Required = Required.Always)]
        public long Protocol { get; set; } = 1;

        [JsonProperty("journal", Required = Required.Always)]
        public JournalInfo Journal { get; set; } = default!;

        [JsonProperty("head", Required = Required.Always)]
        public long Head { get; set; }

        [JsonProperty("resumed", Required = Required.Always)]
        public bool Resumed { get; set; }

        [JsonProperty("server_time", Required = Required.Always)]
        public string ServerTime { get; set; } = default!;

        [JsonProperty("command_policies", Required = Required.Always)]
        public List<CommandPolicy> CommandPolicies { get; set; } = new List<CommandPolicy>();
    }

    public sealed class SnapshotMessage : ServerMessage
    {
        protected override string Discriminator => "snapshot";

        [JsonProperty("snapshot", Required = Required.Always)]
        public Snapshot Snapshot { get; set; } = default!;
    }

    public sealed class EventMessage : ServerMessage
    {
        protected override string Discriminator => "event";

        [JsonProperty("position", Required = Required.Always)]
        public long Position { get; set; }

        [JsonProperty("event", Required = Required.Always)]
        public EventEnvelope Event { get; set; } = default!;

        [JsonProperty("changes", Required = Required.Always)]
        public EntityChanges Changes { get; set; } = default!;
    }

    public sealed class CommandAckMessage : ServerMessage
    {
        protected override string Discriminator => "command_ack";

        [JsonProperty("command_id", Required = Required.Always)]
        public string CommandId { get; set; } = default!;

        [JsonProperty("disposition", Required = Required.Always)]
        public CommandAckDisposition Disposition { get; set; }

        [JsonProperty("command", Required = Required.AllowNull)]
        public CommandView? Command { get; set; }
    }

    public sealed class PongMessage : ServerMessage
    {
        protected override string Discriminator => "pong";

        [JsonProperty("nonce", Required = Required.AllowNull)]
        public string? Nonce { get; set; }
    }

    public sealed class ErrorMessage : ServerMessage
    {
        protected override string Discriminator => "error";

        [JsonProperty("error", Required = Required.Always)]
        public ErrorBody Error { get; set; } = default!;

        [JsonProperty("fatal", Required = Required.Always)]
        public bool Fatal { get; set; }
    }

    public sealed class ResumeCursor
    {
        [JsonProperty("journal_id", Required = Required.Always)]
        public string JournalId { get; set; } = default!;

        [JsonProperty("position", Required = Required.Always)]
        public long Position { get; set; }
    }

    [JsonConverter(typeof(ClientMessageConverter))]
    public abstract class ClientMessage
    {
        [JsonProperty("type", Order = -2)]
        public string Type => Discriminator;

        protected abstract string Discriminator { get; }
    }

    public sealed class ClientMessageConverter : JsonConverter
    {
        public override bool CanWrite => false;

        public override bool CanConvert(Type objectType) => typeof(ClientMessage).IsAssignableFrom(objectType);

        public override object? ReadJson(JsonReader reader, Type objectType, object? existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var item = JObject.Load(reader);
            var token = item["type"];
            var tag = token != null && token.Type == JTokenType.String ? (string?)token : null;
            ClientMessage value = tag switch
            {
                "hello" => new HelloMessage(),
                "command" => new CommandMessage(),
                "ping" => new PingMessage(),
                _ => throw new JsonSerializationException(tag == null
                    ? "ClientMessage has no string type."
                    : "Unknown type \"" + tag + "\" for ClientMessage."),
            };
            if (!objectType.IsInstanceOfType(value))
            {
                throw new JsonSerializationException(
                    "Expected " + objectType.Name + " but type is \"" + tag + "\".");
            }
            using (var itemReader = item.CreateReader())
            {
                serializer.Populate(itemReader, value);
            }
            return value;
        }

        public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer) =>
            throw new NotSupportedException("Variants serialize as themselves.");
    }

    public sealed class HelloMessage : ClientMessage
    {
        protected override string Discriminator => "hello";

        [JsonProperty("protocol", Required = Required.Always)]
        public long Protocol { get; set; } = 1;

        [JsonProperty("client", Required = Required.Always)]
        public ClientInfo Client { get; set; } = default!;

        [JsonProperty("resume", Required = Required.AllowNull)]
        public ResumeCursor? Resume { get; set; }
    }

    public sealed class CommandMessage : ClientMessage
    {
        protected override string Discriminator => "command";

        [JsonProperty("command", Required = Required.Always)]
        public CommandEnvelope Command { get; set; } = default!;
    }

    public sealed class PingMessage : ClientMessage
    {
        protected override string Discriminator => "ping";

        [JsonProperty("nonce", Required = Required.AllowNull)]
        public string? Nonce { get; set; }
    }

    public sealed class HealthResponse
    {
        [JsonProperty("status", Required = Required.Always)]
        public string Status { get; set; } = "ok";
    }

    public sealed class ProjectsResponse
    {
        [JsonProperty("journal", Required = Required.Always)]
        public JournalInfo Journal { get; set; } = default!;

        [JsonProperty("position", Required = Required.Always)]
        public long Position { get; set; }

        [JsonProperty("projects", Required = Required.Always)]
        public List<ProjectView> Projects { get; set; } = new List<ProjectView>();
    }

    public sealed class WorkstreamsResponse
    {
        [JsonProperty("journal", Required = Required.Always)]
        public JournalInfo Journal { get; set; } = default!;

        [JsonProperty("position", Required = Required.Always)]
        public long Position { get; set; }

        [JsonProperty("workstreams", Required = Required.Always)]
        public List<WorkstreamView> Workstreams { get; set; } = new List<WorkstreamView>();
    }

    public sealed class RuntimesResponse
    {
        [JsonProperty("runtimes", Required = Required.Always)]
        public List<RuntimeDescriptor> Runtimes { get; set; } = new List<RuntimeDescriptor>();
    }

    public sealed class StoredEvent
    {
        [JsonProperty("position", Required = Required.Always)]
        public long Position { get; set; }

        [JsonProperty("event", Required = Required.Always)]
        public EventEnvelope Event { get; set; } = default!;
    }

    public sealed class EventsResponse
    {
        [JsonProperty("journal", Required = Required.Always)]
        public JournalInfo Journal { get; set; } = default!;

        [JsonProperty("head", Required = Required.Always)]
        public long Head { get; set; }

        [JsonProperty("events", Required = Required.Always)]
        public List<StoredEvent> Events { get; set; } = new List<StoredEvent>();
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum SubmissionDisposition
    {
        [EnumMember(Value = "accepted")] Accepted,
        [EnumMember(Value = "rejected")] Rejected,
        [EnumMember(Value = "duplicate")] Duplicate,
    }

    public sealed class CommandSubmissionResponse
    {
        [JsonProperty("disposition", Required = Required.Always)]
        public SubmissionDisposition Disposition { get; set; }

        [JsonProperty("command", Required = Required.Always)]
        public CommandView Command { get; set; } = default!;
    }

    public sealed class ErrorResponse
    {
        [JsonProperty("error", Required = Required.Always)]
        public ErrorBody Error { get; set; } = default!;
    }

    public sealed class UnderstandingSourceContract
    {
        [JsonProperty("name", Required = Required.Always)]
        public string Name { get; set; } = default!;

        [JsonProperty("major", Required = Required.Always)]
        public long Major { get; set; }

        [JsonProperty("minor", Required = Required.Always)]
        public long Minor { get; set; }
    }

    public sealed class UnderstandingSource
    {
        [JsonProperty("system", Required = Required.Always)]
        public string System { get; set; } = "salidium";

        [JsonProperty("version", Required = Required.Always)]
        public string Version { get; set; } = default!;

        [JsonProperty("contract", Required = Required.Always)]
        public UnderstandingSourceContract Contract { get; set; } = default!;

        [JsonProperty("instance_id", Required = Required.Always)]
        public string InstanceId { get; set; } = default!;

        [JsonProperty("generated_at", Required = Required.Always)]
        public string GeneratedAt { get; set; } = default!;

        [JsonProperty("evidence_sequence", Required = Required.Always)]
        public long EvidenceSequence { get; set; }
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum UnderstandingVerdictTone
    {
        [EnumMember(Value = "pass")] Pass,
        [EnumMember(Value = "fail")] Fail,
        [EnumMember(Value = "attention")] Attention,
        [EnumMember(Value = "working")] Working,
        [EnumMember(Value = "neutral")] Neutral,
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum UnderstandingEpistemic
    {
        [EnumMember(Value = "observed")] Observed,
        [EnumMember(Value = "reported")] Reported,
        [EnumMember(Value = "inferred")] Inferred,
        [EnumMember(Value = "planned")] Planned,
        [EnumMember(Value = "explained")] Explained,
    }

    public sealed class UnderstandingVerdict
    {
        [JsonProperty("headline", Required = Required.Always)]
        public string Headline { get; set; } = default!;

        [JsonProperty("tone", Required = Required.Always)]
        public UnderstandingVerdictTone Tone { get; set; }

        [JsonProperty("because", Required = Required.AllowNull)]
        public string? Because { get; set; }

        [JsonProperty("at", Required = Required.AllowNull)]
        public string? At { get; set; }

        [JsonProperty("epistemic", Required = Required.Always)]
        public UnderstandingEpistemic Epistemic { get; set; }
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum UnderstandingStatementAuthor
    {
        [EnumMember(Value = "agent")] Agent,
        [EnumMember(Value = "subagent")] Subagent,
        [EnumMember(Value = "user")] User,
    }

    public sealed class UnderstandingStatement
    {
        [JsonProperty("text", Required = Required.Always)]
        public string Text { get; set; } = default!;

        [JsonProperty("author", Required = Required.AllowNull)]
        public UnderstandingStatementAuthor? Author { get; set; }

        [JsonProperty("at", Required = Required.AllowNull)]
        public string? At { get; set; }

        [JsonProperty("epistemic", Required = Required.Always)]
        public UnderstandingEpistemic Epistemic { get; set; }
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum UnderstandingChangeKind
    {
        [EnumMember(Value = "add")] Add,
        [EnumMember(Value = "update")] Update,
        [EnumMember(Value = "delete")] Delete,
        [EnumMember(Value = "move")] Move,
    }

    public sealed class UnderstandingChangedFileCoverage
    {
        [JsonProperty("verified_after", Required = Required.Always)]
        public bool VerifiedAfter { get; set; }

        [JsonProperty("by", Required = Required.AllowNull)]
        public string? By { get; set; }

        [JsonProperty("epistemic", Required = Required.Always)]
        public string Epistemic { get; set; } = "inferred";
    }

    public sealed class UnderstandingChangedFile
    {
        [JsonProperty("path", Required = Required.Always)]
        public string Path { get; set; } = default!;

        [JsonProperty("change_count", Required = Required.Always)]
        public long ChangeCount { get; set; }

        [JsonProperty("lines_added", Required = Required.Always)]
        public long LinesAdded { get; set; }

        [JsonProperty("lines_removed", Required = Required.Always)]
        public long LinesRemoved { get; set; }

        [JsonProperty("kinds", Required = Required.Always)]
        public List<UnderstandingChangeKind> Kinds { get; set; } = new List<UnderstandingChangeKind>();

        [JsonProperty("last_changed_at", Required = Required.Always)]
        public string LastChangedAt { get; set; } = default!;

        [JsonProperty("coverage", Required = Required.Always)]
        public UnderstandingChangedFileCoverage Coverage { get; set; } = default!;

        [JsonProperty("reason", Required = Required.AllowNull)]
        public UnderstandingStatement? Reason { get; set; }
    }

    public sealed class UnderstandingCommit
    {
        [JsonProperty("sha", Required = Required.Always)]
        public string Sha { get; set; } = default!;

        [JsonProperty("at", Required = Required.Always)]
        public string At { get; set; } = default!;
    }

    public sealed class UnderstandingChanges
    {
        [JsonProperty("summary", Required = Required.Always)]
        public string Summary { get; set; } = default!;

        [JsonProperty("files", Required = Required.Always)]
        public List<UnderstandingChangedFile> Files { get; set; } = new List<UnderstandingChangedFile>();

        [JsonProperty("commits", Required = Required.Always)]
        public List<UnderstandingCommit> Commits { get; set; } = new List<UnderstandingCommit>();
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum UnderstandingVerificationRunMethod
    {
        [EnumMember(Value = "test")] Test,
        [EnumMember(Value = "typecheck")] Typecheck,
        [EnumMember(Value = "lint")] Lint,
        [EnumMember(Value = "build")] Build,
        [EnumMember(Value = "other")] Other,
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum UnderstandingVerificationRunOutcome
    {
        [EnumMember(Value = "pass")] Pass,
        [EnumMember(Value = "fail")] Fail,
        [EnumMember(Value = "partial")] Partial,
        [EnumMember(Value = "unknown")] Unknown,
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum UnderstandingVerificationRunScope
    {
        [EnumMember(Value = "full")] Full,
        [EnumMember(Value = "partial")] Partial,
        [EnumMember(Value = "unknown")] Unknown,
    }

    public sealed class UnderstandingVerificationRunCounts
    {
        [JsonProperty("passed", Required = Required.AllowNull)]
        public long? Passed { get; set; }

        [JsonProperty("failed", Required = Required.AllowNull)]
        public long? Failed { get; set; }

        [JsonProperty("skipped", Required = Required.AllowNull)]
        public long? Skipped { get; set; }

        [JsonProperty("total", Required = Required.AllowNull)]
        public long? Total { get; set; }
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum UnderstandingVerificationRunExitObservation
    {
        [EnumMember(Value = "explicit")] Explicit,
        [EnumMember(Value = "inferred_success")] InferredSuccess,
        [EnumMember(Value = "inferred_failure")] InferredFailure,
        [EnumMember(Value = "unknown")] Unknown,
    }

    public sealed class UnderstandingVerificationRunExit
    {
        [JsonProperty("code", Required = Required.AllowNull)]
        public long? Code { get; set; }

        [JsonProperty("observation", Required = Required.Always)]
        public UnderstandingVerificationRunExitObservation Observation { get; set; }
    }

    public sealed class UnderstandingVerificationRun
    {
        [JsonProperty("method", Required = Required.Always)]
        public UnderstandingVerificationRunMethod Method { get; set; }

        [JsonProperty("runner", Required = Required.AllowNull)]
        public string? Runner { get; set; }

        [JsonProperty("label", Required = Required.Always)]
        public string Label { get; set; } = default!;

        [JsonProperty("outcome", Required = Required.Always)]
        public UnderstandingVerificationRunOutcome Outcome { get; set; }

        [JsonProperty("at", Required = Required.Always)]
        public string At { get; set; } = default!;

        [JsonProperty("scope", Required = Required.Always)]
        public UnderstandingVerificationRunScope Scope { get; set; }

        [JsonProperty("counts", Required = Required.AllowNull)]
        public UnderstandingVerificationRunCounts? Counts { get; set; }

        [JsonProperty("exit", Required = Required.Always)]
        public UnderstandingVerificationRunExit Exit { get; set; } = default!;

        [JsonProperty("caveats", Required = Required.Always)]
        public List<string> Caveats { get; set; } = new List<string>();

        [JsonProperty("stale", Required = Required.Always)]
        public bool Stale { get; set; }

        [JsonProperty("later_unreadable", Required = Required.Always)]
        public long LaterUnreadable { get; set; }

        [JsonProperty("epistemic", Required = Required.Always)]
        public UnderstandingEpistemic Epistemic { get; set; }
    }

    public sealed class UnderstandingVerification
    {
        [JsonProperty("summary", Required = Required.Always)]
        public string Summary { get; set; } = default!;

        [JsonProperty("latest_by_method", Required = Required.Always)]
        public List<UnderstandingVerificationRun> LatestByMethod { get; set; } = new List<UnderstandingVerificationRun>();

        [JsonProperty("unverified_files", Required = Required.Always)]
        public List<string> UnverifiedFiles { get; set; } = new List<string>();

        [JsonProperty("statements", Required = Required.Always)]
        public List<UnderstandingStatement> Statements { get; set; } = new List<UnderstandingStatement>();
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum UnderstandingReviewGroupSeverity
    {
        [EnumMember(Value = "info")] Info,
        [EnumMember(Value = "low")] Low,
        [EnumMember(Value = "medium")] Medium,
        [EnumMember(Value = "high")] High,
    }

    public sealed class UnderstandingReviewItem
    {
        [JsonProperty("label", Required = Required.Always)]
        public string Label { get; set; } = default!;

        [JsonProperty("instance", Required = Required.AllowNull)]
        public string? Instance { get; set; }

        [JsonProperty("created_at", Required = Required.Always)]
        public string CreatedAt { get; set; } = default!;

        [JsonProperty("repeats", Required = Required.Always)]
        public long Repeats { get; set; }

        [JsonProperty("epistemic", Required = Required.Always)]
        public UnderstandingEpistemic Epistemic { get; set; }
    }

    public sealed class UnderstandingReviewGroup
    {
        [JsonProperty("rule", Required = Required.Always)]
        public string Rule { get; set; } = default!;

        [JsonProperty("label", Required = Required.Always)]
        public string Label { get; set; } = default!;

        [JsonProperty("severity", Required = Required.Always)]
        public UnderstandingReviewGroupSeverity Severity { get; set; }

        [JsonProperty("occurrences", Required = Required.Always)]
        public long Occurrences { get; set; }

        [JsonProperty("latest_at", Required = Required.Always)]
        public string LatestAt { get; set; } = default!;

        [JsonProperty("items", Required = Required.Always)]
        public List<UnderstandingReviewItem> Items { get; set; } = new List<UnderstandingReviewItem>();
    }

    public sealed class UnderstandingReview
    {
        [JsonProperty("summary", Required = Required.Always)]
        public string Summary { get; set; } = default!;

        [JsonProperty("open", Required = Required.Always)]
        public long Open { get; set; }

        [JsonProperty("resolved", Required = Required.Always)]
        public long Resolved { get; set; }

        [JsonProperty("groups", Required = Required.Always)]
        public List<UnderstandingReviewGroup> Groups { get; set; } = new List<UnderstandingReviewGroup>();
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum UnderstandingRemainingItemStatus
    {
        [EnumMember(Value = "pending")] Pending,
        [EnumMember(Value = "in_progress")] InProgress,
        [EnumMember(Value = "failing")] Failing,
        [EnumMember(Value = "reported")] Reported,
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum UnderstandingRemainingItemSource
    {
        [EnumMember(Value = "plan")] Plan,
        [EnumMember(Value = "verification")] Verification,
        [EnumMember(Value = "agent")] Agent,
    }

    public sealed class UnderstandingRemainingItem
    {
        [JsonProperty("text", Required = Required.Always)]
        public string Text { get; set; } = default!;

        [JsonProperty("status", Required = Required.Always)]
        public UnderstandingRemainingItemStatus Status { get; set; }

        [JsonProperty("source", Required = Required.Always)]
        public UnderstandingRemainingItemSource Source { get; set; }

        [JsonProperty("epistemic", Required = Required.Always)]
        public UnderstandingEpistemic Epistemic { get; set; }
    }

    public sealed class UnderstandingRemaining
    {
        [JsonProperty("summary", Required = Required.Always)]
        public string Summary { get; set; } = default!;

        [JsonProperty("items", Required = Required.Always)]
        public List<UnderstandingRemainingItem> Items { get; set; } = new List<UnderstandingRemainingItem>();
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum UnderstandingExplanationStatus
    {
        [EnumMember(Value = "generated")] Generated,
        [EnumMember(Value = "generating")] Generating,
        [EnumMember(Value = "disabled")] Disabled,
        [EnumMember(Value = "unavailable")] Unavailable,
        [EnumMember(Value = "failed")] Failed,
        [EnumMember(Value = "none")] None,
    }

    public sealed class UnderstandingExplanationContentWhat
    {
        [JsonProperty("summary", Required = Required.Always)]
        public string Summary { get; set; } = default!;

        [JsonProperty("currently", Required = Required.AllowNull)]
        public string? Currently { get; set; }
    }

    public sealed class UnderstandingExplanationLane
    {
        [JsonProperty("title", Required = Required.Always)]
        public string Title { get; set; } = default!;

        [JsonProperty("steps", Required = Required.Always)]
        public List<string> Steps { get; set; } = new List<string>();
    }

    public sealed class UnderstandingExplanationContentWhy
    {
        [JsonProperty("summary", Required = Required.Always)]
        public string Summary { get; set; } = default!;

        [JsonProperty("lanes", Required = Required.Always)]
        public List<UnderstandingExplanationLane> Lanes { get; set; } = new List<UnderstandingExplanationLane>();

        [JsonProperty("chain", Required = Required.Always)]
        public List<string> Chain { get; set; } = new List<string>();
    }

    public sealed class UnderstandingExplanationContentHow
    {
        [JsonProperty("summary", Required = Required.Always)]
        public string Summary { get; set; } = default!;

        [JsonProperty("root", Required = Required.AllowNull)]
        public string? Root { get; set; }

        [JsonProperty("steps", Required = Required.Always)]
        public List<string> Steps { get; set; } = new List<string>();
    }

    public sealed class UnderstandingExplanationContentApproachChange
    {
        [JsonProperty("from", Required = Required.Always)]
        public string From { get; set; } = default!;

        [JsonProperty("from_steps", Required = Required.Always)]
        public List<string> FromSteps { get; set; } = new List<string>();

        [JsonProperty("why", Required = Required.Always)]
        public string Why { get; set; } = default!;

        [JsonProperty("to", Required = Required.Always)]
        public string To { get; set; } = default!;

        [JsonProperty("to_steps", Required = Required.Always)]
        public List<string> ToSteps { get; set; } = new List<string>();
    }

    public sealed class UnderstandingExplanationContent
    {
        [JsonProperty("what", Required = Required.Always)]
        public UnderstandingExplanationContentWhat What { get; set; } = default!;

        [JsonProperty("why", Required = Required.Always)]
        public UnderstandingExplanationContentWhy Why { get; set; } = default!;

        [JsonProperty("how", Required = Required.Always)]
        public UnderstandingExplanationContentHow How { get; set; } = default!;

        [JsonProperty("approach_change", Required = Required.AllowNull)]
        public UnderstandingExplanationContentApproachChange? ApproachChange { get; set; }
    }

    public sealed class UnderstandingExplanation
    {
        [JsonProperty("status", Required = Required.Always)]
        public UnderstandingExplanationStatus Status { get; set; }

        [JsonProperty("current", Required = Required.Always)]
        public bool Current { get; set; }

        [JsonProperty("based_on_sequence", Required = Required.AllowNull)]
        public long? BasedOnSequence { get; set; }

        [JsonProperty("generated_at", Required = Required.AllowNull)]
        public string? GeneratedAt { get; set; }

        [JsonProperty("model", Required = Required.AllowNull)]
        public string? Model { get; set; }

        [JsonProperty("epistemic", Required = Required.Always)]
        public string Epistemic { get; set; } = "explained";

        [JsonProperty("content", Required = Required.AllowNull)]
        public UnderstandingExplanationContent? Content { get; set; }
    }

    public sealed class Understanding
    {
        [JsonProperty("source", Required = Required.Always)]
        public UnderstandingSource Source { get; set; } = default!;

        [JsonProperty("verdict", Required = Required.Always)]
        public UnderstandingVerdict Verdict { get; set; } = default!;

        [JsonProperty("latest_statement", Required = Required.AllowNull)]
        public UnderstandingStatement? LatestStatement { get; set; }

        [JsonProperty("changes", Required = Required.Always)]
        public UnderstandingChanges Changes { get; set; } = default!;

        [JsonProperty("verification", Required = Required.Always)]
        public UnderstandingVerification Verification { get; set; } = default!;

        [JsonProperty("review", Required = Required.Always)]
        public UnderstandingReview Review { get; set; } = default!;

        [JsonProperty("remaining", Required = Required.Always)]
        public UnderstandingRemaining Remaining { get; set; } = default!;

        [JsonProperty("explanation", Required = Required.Always)]
        public UnderstandingExplanation Explanation { get; set; } = default!;
    }

    [JsonConverter(typeof(UnderstandingResultConverter))]
    public abstract class UnderstandingResult
    {
        [JsonProperty("availability", Order = -2)]
        public string Availability => Discriminator;

        protected abstract string Discriminator { get; }
    }

    public sealed class UnderstandingResultConverter : JsonConverter
    {
        public override bool CanWrite => false;

        public override bool CanConvert(Type objectType) => typeof(UnderstandingResult).IsAssignableFrom(objectType);

        public override object? ReadJson(JsonReader reader, Type objectType, object? existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var item = JObject.Load(reader);
            var token = item["availability"];
            var tag = token != null && token.Type == JTokenType.String ? (string?)token : null;
            UnderstandingResult value = tag switch
            {
                "available" => new AvailableUnderstanding(),
                "not_found" => new NotFoundUnderstanding(),
                "unavailable" => new UnavailableUnderstanding(),
                "incompatible" => new IncompatibleUnderstanding(),
                "unauthorized" => new UnauthorizedUnderstanding(),
                _ => throw new JsonSerializationException(tag == null
                    ? "UnderstandingResult has no string availability."
                    : "Unknown availability \"" + tag + "\" for UnderstandingResult."),
            };
            if (!objectType.IsInstanceOfType(value))
            {
                throw new JsonSerializationException(
                    "Expected " + objectType.Name + " but availability is \"" + tag + "\".");
            }
            using (var itemReader = item.CreateReader())
            {
                serializer.Populate(itemReader, value);
            }
            return value;
        }

        public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer) =>
            throw new NotSupportedException("Variants serialize as themselves.");
    }

    public sealed class AvailableUnderstanding : UnderstandingResult
    {
        protected override string Discriminator => "available";

        [JsonProperty("understanding", Required = Required.Always)]
        public Understanding Understanding { get; set; } = default!;
    }

    public sealed class NotFoundUnderstanding : UnderstandingResult
    {
        protected override string Discriminator => "not_found";

        [JsonProperty("reason", Required = Required.Always)]
        public ErrorInfo Reason { get; set; } = default!;
    }

    public sealed class UnavailableUnderstanding : UnderstandingResult
    {
        protected override string Discriminator => "unavailable";

        [JsonProperty("reason", Required = Required.Always)]
        public ErrorInfo Reason { get; set; } = default!;
    }

    public sealed class IncompatibleUnderstanding : UnderstandingResult
    {
        protected override string Discriminator => "incompatible";

        [JsonProperty("reason", Required = Required.Always)]
        public ErrorInfo Reason { get; set; } = default!;
    }

    public sealed class UnauthorizedUnderstanding : UnderstandingResult
    {
        protected override string Discriminator => "unauthorized";

        [JsonProperty("reason", Required = Required.Always)]
        public ErrorInfo Reason { get; set; } = default!;
    }

    public sealed class UnderstandingResponse
    {
        [JsonProperty("execution_id", Required = Required.Always)]
        public string ExecutionId { get; set; } = default!;

        [JsonProperty("result", Required = Required.Always)]
        public UnderstandingResult Result { get; set; } = default!;
    }
}
