import Type, { type Static, type TSchema } from 'typebox';
import {
  ClientInfo,
  CommandId,
  ExecutionId,
  NativeId,
  Nullable,
  ProjectId,
  RuntimeId,
  Text,
  Timestamp,
  WorkstreamId,
} from './primitives.ts';
import { ModelRef, RuntimeOptions } from './runtime.ts';
import { COMMAND_SCHEMA_VERSION } from './versions.ts';

const strict = { additionalProperties: false } as const;

const CommandBase = {
  schema_version: Type.Literal(COMMAND_SCHEMA_VERSION),
  /** Generated by the client. Resubmitting the same command with the same id is idempotent. */
  command_id: CommandId,
  /** Client clock, recorded for audit. Ordering uses the journal, never this value. */
  issued_at: Timestamp,
  client: ClientInfo,
};

function defineCommand<const T extends string, P extends TSchema>(commandType: T, payload: P) {
  return Type.Object({ ...CommandBase, command_type: Type.Literal(commandType), payload }, strict);
}

export const ProjectCreateCommand = defineCommand(
  'project.create',
  Type.Object({ name: Text(200) }, strict),
);

export const WorkstreamCreateCommand = defineCommand(
  'workstream.create',
  Type.Object({ project_id: ProjectId, title: Text(200), objective: Nullable(Text(4000)) }, strict),
);

export const ExecutionStartCommand = defineCommand(
  'execution.start',
  Type.Object(
    {
      workstream_id: WorkstreamId,
      runtime_id: RuntimeId,
      instruction: Text(32000),
      options: RuntimeOptions,
      /**
       * A model from the runtime's own list (ADR 0016), or null to leave the choice to the
       * runtime. Only for a runtime whose `model_choice` is `listed`; the runtime checks it again
       * against a fresh list before anything runs.
       */
      model_ref: Nullable(ModelRef),
    },
    strict,
  ),
);

export const ExecutionSendInstructionCommand = defineCommand(
  'execution.send_instruction',
  Type.Object({ execution_id: ExecutionId, text: Text(32000) }, strict),
);

export const ApprovalDecision = Type.Union([Type.Literal('approve'), Type.Literal('deny')]);
export type ApprovalDecision = Static<typeof ApprovalDecision>;

export const ExecutionRespondToApprovalCommand = defineCommand(
  'execution.respond_to_approval',
  Type.Object(
    {
      execution_id: ExecutionId,
      approval_id: NativeId,
      decision: ApprovalDecision,
      /** Optional explanation passed to the runtime, for example why a request was denied. */
      message: Nullable(Text(2000)),
    },
    strict,
  ),
);

export const ExecutionInterruptCommand = defineCommand(
  'execution.interrupt',
  Type.Object({ execution_id: ExecutionId }, strict),
);

export const COMMAND_VARIANTS = [
  ProjectCreateCommand,
  WorkstreamCreateCommand,
  ExecutionStartCommand,
  ExecutionSendInstructionCommand,
  ExecutionRespondToApprovalCommand,
  ExecutionInterruptCommand,
] as const;

export const CommandEnvelope = Type.Union([...COMMAND_VARIANTS]);
export type CommandEnvelope = Static<typeof CommandEnvelope>;
export type CommandType = CommandEnvelope['command_type'];
export type CommandOf<T extends CommandType> = Extract<CommandEnvelope, { command_type: T }>;

export const CommandType = Type.Union([
  Type.Literal('project.create'),
  Type.Literal('workstream.create'),
  Type.Literal('execution.start'),
  Type.Literal('execution.send_instruction'),
  Type.Literal('execution.respond_to_approval'),
  Type.Literal('execution.interrupt'),
]);

/**
 * Consequence category of a command, recorded with every accepted command. Clients must require
 * an explicit, deliberate user action for `review_required` and `high_consequence` commands.
 */
export const PolicyCategory = Type.Union([
  Type.Literal('low_consequence'),
  Type.Literal('review_required'),
  Type.Literal('high_consequence'),
]);
export type PolicyCategory = Static<typeof PolicyCategory>;

export const RejectionCode = Type.Union([
  Type.Literal('project_not_found'),
  Type.Literal('workstream_not_found'),
  Type.Literal('execution_not_found'),
  Type.Literal('runtime_not_found'),
  Type.Literal('approval_not_found'),
  Type.Literal('capability_unsupported'),
  Type.Literal('invalid_state'),
  Type.Literal('invalid_runtime_options'),
  /**
   * The client is playing a recorded demonstration on its own device: the command was not sent to
   * any control plane or agent, however admissible it was in the recording. Only the client's
   * demonstration answers with it; a control plane never does.
   */
  Type.Literal('demonstration'),
]);
export type RejectionCode = Static<typeof RejectionCode>;

export const CommandRejection = Type.Object({ code: RejectionCode, message: Text(2000) }, strict);
export type CommandRejection = Static<typeof CommandRejection>;

/**
 * Why an accepted command did not succeed. `effect` states whether the runtime may nevertheless
 * have acted: `unknown` after a timeout means the action may or may not have happened.
 */
export const CommandFailure = Type.Object(
  {
    code: Type.String({ pattern: '^[a-z][a-z0-9_]{0,63}$' }),
    message: Text(2000),
    effect: Type.Union([Type.Literal('none'), Type.Literal('unknown')]),
  },
  strict,
);
export type CommandFailure = Static<typeof CommandFailure>;

export const CommandResult = Type.Union([
  Type.Object({ kind: Type.Literal('project_created'), project_id: ProjectId }, strict),
  Type.Object({ kind: Type.Literal('workstream_created'), workstream_id: WorkstreamId }, strict),
  Type.Object({ kind: Type.Literal('execution_created'), execution_id: ExecutionId }, strict),
]);
export type CommandResult = Static<typeof CommandResult>;

export const ReceivedVia = Type.Union([
  Type.Literal('http'),
  Type.Literal('websocket'),
  Type.Literal('internal'),
]);
export type ReceivedVia = Static<typeof ReceivedVia>;

export { CommandId };
