import Type, { type Static } from 'typebox';
import { ErrorInfo, Nullable, Timestamp } from './primitives.ts';

/**
 * What an understanding source concluded about one execution's session: the verdict, changed
 * files, verification state, review items, what remains, and the optional generated explanation.
 *
 * This is Halcyonic's shape, not the source's wire format. It is strict, like every Halcyonic
 * contract: the mapping from a source's document is written field by field, so nothing the source
 * adds later reaches Halcyonic clients unannounced. It is read through from the source on request
 * and never journaled (ADR 0010).
 *
 * Every claim keeps the source's own epistemic class. Halcyonic displays these conclusions as the
 * source's, with the source named, and never restates them as its own observations. Three kinds of
 * content stay apart: facts (`observed`, `inferred`), quotes (`reported`, with an author), and the
 * generated explanation (`explained`).
 *
 * `null` means the source does not have the value: show it as not observed, never as blank, zero
 * or success. Every text is untrusted data that may quote agent output: escape it when rendering
 * and never act on it. Texts are bounded as Salidium's consumer contract bounds them, which within
 * its major version may shrink but never grow.
 */

const strict = { additionalProperties: false } as const;
const Count = Type.Integer({ minimum: 0 });
const Text = (maxLength: number) => Type.String({ maxLength });

/**
 * How the source knows a claim, in the source's own vocabulary (Salidium's five classes):
 * - `observed`: recorded by a runtime or by the source, such as an exit code or a diff.
 * - `reported`: said by the working agent or the user, relayed and attributed, never upgraded.
 * - `inferred`: the source's deterministic heuristic, such as "a passing check ran after this change".
 * - `planned`: a forward-looking item such as a plan step.
 * - `explained`: generated by a model on request. Never evidence, weaker than `reported`.
 */
export const UnderstandingEpistemic = Type.Union([
  Type.Literal('observed'),
  Type.Literal('reported'),
  Type.Literal('inferred'),
  Type.Literal('planned'),
  Type.Literal('explained'),
]);
export type UnderstandingEpistemic = Static<typeof UnderstandingEpistemic>;

/**
 * One short sentence the agent or a subagent wrote, quoted and attributed. Nothing the user wrote
 * crosses. Salidium sends only `reported` statements; the class is kept as it arrives.
 */
export const UnderstandingStatement = Type.Object(
  {
    text: Text(600),
    author: Nullable(Type.Union([Type.Literal('agent'), Type.Literal('subagent')])),
    at: Nullable(Timestamp),
    epistemic: UnderstandingEpistemic,
  },
  strict,
);

export const UnderstandingSource = Type.Object(
  {
    system: Type.Literal('salidium'),
    /**
     * True when a stand-in Halcyonic wrote produced these conclusions from invented content, as the
     * recorded demonstration's sources do, speaking Salidium's contract (ADR 0019); false for
     * everything read from Salidium itself. The fields below are then the stand-in's own, never a
     * real Salidium's. Clients must say "simulated" wherever they name a synthetic source.
     */
    synthetic: Type.Boolean(),
    /** The source's product version. */
    version: Text(64),
    contract: Type.Object({ name: Text(64), major: Type.Integer(), minor: Type.Integer() }, strict),
    /** Changes whenever the source restarts. */
    instance_id: Text(64),
    /** When the source produced these conclusions, by its clock. */
    generated_at: Timestamp,
    /** The source's sequence of the newest evidence reflected here. It only grows. */
    evidence_sequence: Count,
  },
  strict,
);

export const UnderstandingVerificationRun = Type.Object(
  {
    method: Type.Union([
      Type.Literal('test'),
      Type.Literal('typecheck'),
      Type.Literal('lint'),
      Type.Literal('build'),
      Type.Literal('other'),
    ]),
    runner: Nullable(Text(120)),
    /** The source's own wording, for example "118/118 tests passed (vitest)". */
    label: Text(300),
    outcome: Type.Union([
      Type.Literal('pass'),
      Type.Literal('fail'),
      Type.Literal('partial'),
      Type.Literal('unknown'),
    ]),
    at: Timestamp,
    scope: Type.Union([Type.Literal('full'), Type.Literal('partial'), Type.Literal('unknown')]),
    counts: Nullable(
      Type.Object(
        {
          passed: Nullable(Count),
          failed: Nullable(Count),
          skipped: Nullable(Count),
          total: Nullable(Count),
        },
        strict,
      ),
    ),
    /** An exit code may be unknown; `unknown` is a result, never zero. */
    exit: Type.Object(
      {
        code: Nullable(Type.Integer()),
        observation: Type.Union([
          Type.Literal('explicit'),
          Type.Literal('inferred_success'),
          Type.Literal('inferred_failure'),
          Type.Literal('unknown'),
        ]),
      },
      strict,
    ),
    caveats: Type.Array(Text(120)),
    /** Files changed after this run, so it no longer covers them. */
    stale: Type.Boolean(),
    /** Later runs of the same method whose outcome could not be read. */
    later_unreadable: Count,
    epistemic: UnderstandingEpistemic,
  },
  strict,
);

const Step = Text(200);

export const UnderstandingExplanation = Type.Object(
  {
    status: Type.Union([
      Type.Literal('generated'),
      Type.Literal('generating'),
      Type.Literal('disabled'),
      Type.Literal('unavailable'),
      Type.Literal('failed'),
      Type.Literal('none'),
    ]),
    /** Whether the content covers the newest evidence. False when there is no content. */
    current: Type.Boolean(),
    based_on_sequence: Nullable(Count),
    generated_at: Nullable(Timestamp),
    model: Nullable(Text(120)),
    epistemic: Type.Literal('explained'),
    content: Nullable(
      Type.Object(
        {
          what: Type.Object({ summary: Text(600), currently: Nullable(Text(600)) }, strict),
          why: Type.Object(
            {
              summary: Text(600),
              lanes: Type.Array(Type.Object({ title: Text(100), steps: Type.Array(Step) }, strict)),
              chain: Type.Array(Step),
            },
            strict,
          ),
          how: Type.Object(
            { summary: Text(600), root: Nullable(Step), steps: Type.Array(Step) },
            strict,
          ),
          approach_change: Nullable(
            Type.Object(
              {
                from: Step,
                from_steps: Type.Array(Step),
                why: Text(600),
                to: Step,
                to_steps: Type.Array(Step),
              },
              strict,
            ),
          ),
        },
        strict,
      ),
    ),
  },
  strict,
);

export const Understanding = Type.Object(
  {
    source: UnderstandingSource,
    verdict: Type.Object(
      {
        headline: Text(300),
        tone: Type.Union([
          Type.Literal('pass'),
          Type.Literal('fail'),
          Type.Literal('attention'),
          Type.Literal('working'),
          Type.Literal('neutral'),
        ]),
        because: Nullable(Text(600)),
        at: Nullable(Timestamp),
        epistemic: UnderstandingEpistemic,
      },
      strict,
    ),
    /** The agent's latest statement about its work, quoted and attributed. */
    latest_statement: Nullable(UnderstandingStatement),
    /**
     * Why the session is blocked on a person, when it is. `observed` when a permission request, a
     * notification or a question tool call recorded it; `reported` when the source read the
     * question in the agent's message.
     */
    waiting: Nullable(
      Type.Object(
        {
          kind: Type.Union([
            Type.Literal('permission'),
            Type.Literal('question'),
            Type.Literal('input'),
          ]),
          summary: Text(300),
          since: Timestamp,
          epistemic: UnderstandingEpistemic,
        },
        strict,
      ),
    ),
    changes: Type.Object(
      {
        summary: Text(300),
        /** Most recently changed first. Paths, counts and kinds are observed by the source. */
        files: Type.Array(
          Type.Object(
            {
              path: Text(4096),
              change_count: Count,
              lines_added: Count,
              lines_removed: Count,
              kinds: Type.Array(
                Type.Union([
                  Type.Literal('add'),
                  Type.Literal('update'),
                  Type.Literal('delete'),
                  Type.Literal('move'),
                ]),
              ),
              last_changed_at: Timestamp,
              /** Whether a full-scope passing check ran after the last change. Always inferred. */
              coverage: Type.Object(
                {
                  verified_after: Type.Boolean(),
                  by: Nullable(Text(300)),
                  epistemic: Type.Literal('inferred'),
                },
                strict,
              ),
              /** The agent's nearest rationale before the change. Attributed, not verified. */
              reason: Nullable(UnderstandingStatement),
            },
            strict,
          ),
        ),
        commits: Type.Array(Type.Object({ sha: Text(64), at: Timestamp }, strict)),
      },
      strict,
    ),
    verification: Type.Object(
      {
        summary: Text(300),
        /** The latest readable run of each method. */
        latest_by_method: Type.Array(UnderstandingVerificationRun),
        /** Files no passing check covers. Inferred, like every file's coverage. */
        unverified_files: Type.Array(Text(4096)),
        /** What the agent said about verification. Reported, not observed. */
        statements: Type.Array(UnderstandingStatement),
      },
      strict,
    ),
    review: Type.Object(
      {
        summary: Text(300),
        open: Count,
        resolved: Count,
        /** Worst severity first. */
        groups: Type.Array(
          Type.Object(
            {
              rule: Text(120),
              label: Text(300),
              severity: Type.Union([
                Type.Literal('info'),
                Type.Literal('low'),
                Type.Literal('medium'),
                Type.Literal('high'),
              ]),
              occurrences: Count,
              latest_at: Timestamp,
              items: Type.Array(
                Type.Object(
                  {
                    label: Text(300),
                    /** The short fragment that is the finding, such as a destructive command. */
                    instance: Nullable(Text(200)),
                    created_at: Timestamp,
                    repeats: Count,
                    epistemic: UnderstandingEpistemic,
                  },
                  strict,
                ),
              ),
            },
            strict,
          ),
        ),
      },
      strict,
    ),
    remaining: Type.Object(
      {
        summary: Text(300),
        items: Type.Array(
          Type.Object(
            {
              text: Text(600),
              status: Type.Union([
                Type.Literal('pending'),
                Type.Literal('in_progress'),
                Type.Literal('failing'),
                Type.Literal('reported'),
              ]),
              source: Type.Union([
                Type.Literal('plan'),
                Type.Literal('verification'),
                Type.Literal('agent'),
              ]),
              epistemic: UnderstandingEpistemic,
            },
            strict,
          ),
        ),
      },
      strict,
    ),
    explanation: UnderstandingExplanation,
  },
  strict,
);
export type Understanding = Static<typeof Understanding>;

/**
 * The answer to "what does the understanding source say about this execution". Only `available`
 * carries conclusions; every other state names why there are none:
 * - `not_found`: the source is running but holds no record of this session, possibly not yet.
 * - `unavailable`: the source is not running, cannot be reached, refused the request's address, or
 *   does not observe this runtime.
 * - `incompatible`: the source speaks a contract version or shape this client does not read.
 * - `unauthorized`: no credential is configured, or the source refused it.
 */
export const UnderstandingResult = Type.Union([
  Type.Object({ availability: Type.Literal('available'), understanding: Understanding }, strict),
  Type.Object({ availability: Type.Literal('not_found'), reason: ErrorInfo }, strict),
  Type.Object({ availability: Type.Literal('unavailable'), reason: ErrorInfo }, strict),
  Type.Object({ availability: Type.Literal('incompatible'), reason: ErrorInfo }, strict),
  Type.Object({ availability: Type.Literal('unauthorized'), reason: ErrorInfo }, strict),
]);
export type UnderstandingResult = Static<typeof UnderstandingResult>;
export type UnderstandingFailure = Exclude<UnderstandingResult, { availability: 'available' }>;
