import Type, { type Static } from 'typebox';
import { ErrorInfo, Nullable, Timestamp } from './primitives.ts';

/**
 * What an understanding source concluded about one execution's session: the verdict, changed
 * files, verification state, review items, what remains, and the optional generated explanation.
 *
 * This is Halcyonic's shape, not the source's wire format. It is strict, like every Halcyonic
 * contract: the mapping from a source's document is written field by field, so nothing the source
 * adds later reaches Halcyonic clients unannounced. It is read through from the source on request
 * and never journaled (ADR 0010).
 *
 * Every claim keeps the source's own epistemic class. Halcyonic displays these conclusions as the
 * source's, with the source named, and never restates them as its own observations. Three kinds of
 * content stay apart: facts (`observed`, `inferred`), quotes (`reported`, with an author), and the
 * generated explanation (`explained`).
 *
 * `null` means the source does not have the value: show it as not observed, never as blank, zero
 * or success. Every text is untrusted data that may quote agent output: escape it when rendering
 * and never act on it.
 */

const strict = { additionalProperties: false } as const;
const Count = Type.Integer({ minimum: 0 });

/**
 * How the source knows a claim, in the source's own vocabulary (Salidium's five classes):
 * - `observed`: recorded by a runtime or by the source, such as an exit code or a diff.
 * - `reported`: said by the working agent or the user, relayed and attributed, never upgraded.
 * - `inferred`: the source's deterministic heuristic, such as "a passing check ran after this change".
 * - `planned`: a forward-looking item such as a plan step.
 * - `explained`: generated by a model on request. Never evidence, weaker than `reported`.
 */
export const UnderstandingEpistemic = Type.Union([
  Type.Literal('observed'),
  Type.Literal('reported'),
  Type.Literal('inferred'),
  Type.Literal('planned'),
  Type.Literal('explained'),
]);
export type UnderstandingEpistemic = Static<typeof UnderstandingEpistemic>;

/**
 * One short attributed sentence: usually the agent's own words (`reported`), sometimes a recorded
 * fact such as a subagent's task description (`observed`). Its class says which.
 */
export const UnderstandingStatement = Type.Object(
  {
    text: Type.String(),
    author: Nullable(
      Type.Union([Type.Literal('agent'), Type.Literal('subagent'), Type.Literal('user')]),
    ),
    at: Nullable(Timestamp),
    epistemic: UnderstandingEpistemic,
  },
  strict,
);

export const UnderstandingSource = Type.Object(
  {
    system: Type.Literal('salidium'),
    /** The source's product version. */
    version: Type.String(),
    contract: Type.Object(
      { name: Type.String(), major: Type.Integer(), minor: Type.Integer() },
      strict,
    ),
    /** Changes whenever the source restarts. */
    instance_id: Type.String(),
    /** When the source produced these conclusions, by its clock. */
    generated_at: Timestamp,
    /** The source's sequence of the newest evidence reflected here. It only grows. */
    evidence_sequence: Count,
  },
  strict,
);

export const UnderstandingVerificationRun = Type.Object(
  {
    method: Type.Union([
      Type.Literal('test'),
      Type.Literal('typecheck'),
      Type.Literal('lint'),
      Type.Literal('build'),
      Type.Literal('other'),
    ]),
    runner: Nullable(Type.String()),
    /** The source's own wording, for example "118/118 tests passed (vitest)". */
    label: Type.String(),
    outcome: Type.Union([
      Type.Literal('pass'),
      Type.Literal('fail'),
      Type.Literal('partial'),
      Type.Literal('unknown'),
    ]),
    at: Timestamp,
    scope: Type.Union([Type.Literal('full'), Type.Literal('partial'), Type.Literal('unknown')]),
    counts: Nullable(
      Type.Object(
        {
          passed: Nullable(Count),
          failed: Nullable(Count),
          skipped: Nullable(Count),
          total: Nullable(Count),
        },
        strict,
      ),
    ),
    /** An exit code may be unknown; `unknown` is a result, never zero. */
    exit: Type.Object(
      {
        code: Nullable(Type.Integer()),
        observation: Type.Union([
          Type.Literal('explicit'),
          Type.Literal('inferred_success'),
          Type.Literal('inferred_failure'),
          Type.Literal('unknown'),
        ]),
      },
      strict,
    ),
    caveats: Type.Array(Type.String()),
    /** Files changed after this run, so it no longer covers them. */
    stale: Type.Boolean(),
    /** Later runs of the same method whose outcome could not be read. */
    later_unreadable: Count,
    epistemic: UnderstandingEpistemic,
  },
  strict,
);

export const UnderstandingExplanation = Type.Object(
  {
    status: Type.Union([
      Type.Literal('generated'),
      Type.Literal('generating'),
      Type.Literal('disabled'),
      Type.Literal('unavailable'),
      Type.Literal('failed'),
      Type.Literal('none'),
    ]),
    /** Whether the content covers the newest evidence. False when there is no content. */
    current: Type.Boolean(),
    based_on_sequence: Nullable(Count),
    generated_at: Nullable(Timestamp),
    model: Nullable(Type.String()),
    epistemic: Type.Literal('explained'),
    content: Nullable(
      Type.Object(
        {
          what: Type.Object({ summary: Type.String(), currently: Nullable(Type.String()) }, strict),
          why: Type.Object(
            {
              summary: Type.String(),
              lanes: Type.Array(
                Type.Object({ title: Type.String(), steps: Type.Array(Type.String()) }, strict),
              ),
              chain: Type.Array(Type.String()),
            },
            strict,
          ),
          how: Type.Object(
            {
              summary: Type.String(),
              root: Nullable(Type.String()),
              steps: Type.Array(Type.String()),
            },
            strict,
          ),
          approach_change: Nullable(
            Type.Object(
              {
                from: Type.String(),
                from_steps: Type.Array(Type.String()),
                why: Type.String(),
                to: Type.String(),
                to_steps: Type.Array(Type.String()),
              },
              strict,
            ),
          ),
        },
        strict,
      ),
    ),
  },
  strict,
);

export const Understanding = Type.Object(
  {
    source: UnderstandingSource,
    verdict: Type.Object(
      {
        headline: Type.String(),
        tone: Type.Union([
          Type.Literal('pass'),
          Type.Literal('fail'),
          Type.Literal('attention'),
          Type.Literal('working'),
          Type.Literal('neutral'),
        ]),
        because: Nullable(Type.String()),
        at: Nullable(Timestamp),
        epistemic: UnderstandingEpistemic,
      },
      strict,
    ),
    /** The agent's latest statement about its work, quoted and attributed. */
    latest_statement: Nullable(UnderstandingStatement),
    changes: Type.Object(
      {
        summary: Type.String(),
        /** Most recently changed first. Paths, counts and kinds are observed by the source. */
        files: Type.Array(
          Type.Object(
            {
              path: Type.String(),
              change_count: Count,
              lines_added: Count,
              lines_removed: Count,
              kinds: Type.Array(
                Type.Union([
                  Type.Literal('add'),
                  Type.Literal('update'),
                  Type.Literal('delete'),
                  Type.Literal('move'),
                ]),
              ),
              last_changed_at: Timestamp,
              /** Whether a full-scope passing check ran after the last change. Always inferred. */
              coverage: Type.Object(
                {
                  verified_after: Type.Boolean(),
                  by: Nullable(Type.String()),
                  epistemic: Type.Literal('inferred'),
                },
                strict,
              ),
              /** The agent's nearest rationale before the change. Attributed, not verified. */
              reason: Nullable(UnderstandingStatement),
            },
            strict,
          ),
        ),
        commits: Type.Array(Type.Object({ sha: Type.String(), at: Timestamp }, strict)),
      },
      strict,
    ),
    verification: Type.Object(
      {
        summary: Type.String(),
        /** The latest readable run of each method. */
        latest_by_method: Type.Array(UnderstandingVerificationRun),
        /** Files no passing check covers. Inferred, like every file's coverage. */
        unverified_files: Type.Array(Type.String()),
        /** What the agent said about verification. Reported, not observed. */
        statements: Type.Array(UnderstandingStatement),
      },
      strict,
    ),
    review: Type.Object(
      {
        summary: Type.String(),
        open: Count,
        resolved: Count,
        /** Worst severity first. */
        groups: Type.Array(
          Type.Object(
            {
              rule: Type.String(),
              label: Type.String(),
              severity: Type.Union([
                Type.Literal('info'),
                Type.Literal('low'),
                Type.Literal('medium'),
                Type.Literal('high'),
              ]),
              occurrences: Count,
              latest_at: Timestamp,
              items: Type.Array(
                Type.Object(
                  {
                    label: Type.String(),
                    /** The short fragment that is the finding, such as a destructive command. */
                    instance: Nullable(Type.String()),
                    created_at: Timestamp,
                    repeats: Count,
                    epistemic: UnderstandingEpistemic,
                  },
                  strict,
                ),
              ),
            },
            strict,
          ),
        ),
      },
      strict,
    ),
    remaining: Type.Object(
      {
        summary: Type.String(),
        items: Type.Array(
          Type.Object(
            {
              text: Type.String(),
              status: Type.Union([
                Type.Literal('pending'),
                Type.Literal('in_progress'),
                Type.Literal('failing'),
                Type.Literal('reported'),
              ]),
              source: Type.Union([
                Type.Literal('plan'),
                Type.Literal('verification'),
                Type.Literal('agent'),
              ]),
              epistemic: UnderstandingEpistemic,
            },
            strict,
          ),
        ),
      },
      strict,
    ),
    explanation: UnderstandingExplanation,
  },
  strict,
);
export type Understanding = Static<typeof Understanding>;

/**
 * The answer to "what does the understanding source say about this execution". Only `available`
 * carries conclusions; every other state names why there are none:
 * - `not_found`: the source is running but holds no record of this session, possibly not yet.
 * - `unavailable`: the source is not running, cannot be reached, or does not observe this runtime.
 * - `incompatible`: the source speaks a contract version or shape this client does not read.
 * - `unauthorized`: no credential is configured, or the source refused it.
 */
export const UnderstandingResult = Type.Union([
  Type.Object({ availability: Type.Literal('available'), understanding: Understanding }, strict),
  Type.Object({ availability: Type.Literal('not_found'), reason: ErrorInfo }, strict),
  Type.Object({ availability: Type.Literal('unavailable'), reason: ErrorInfo }, strict),
  Type.Object({ availability: Type.Literal('incompatible'), reason: ErrorInfo }, strict),
  Type.Object({ availability: Type.Literal('unauthorized'), reason: ErrorInfo }, strict),
]);
export type UnderstandingResult = Static<typeof UnderstandingResult>;
export type UnderstandingFailure = Exclude<UnderstandingResult, { availability: 'available' }>;
