// Generated by apps/xr/tools/glaze_icons.py from Material Symbols Rounded 2.972 (FILL 1, wght 500, GRAD 0, opsz 24).
// Do not edit: change the script's list and run it again (docs/internal/runbooks/XR_DEVELOPMENT.md).
#nullable enable
using System;
using Halcyonic.Client;

namespace Halcyonic.XR.UI
{
    /// <summary>The glyph of every icon in the Glaze icon font: the only code that knows a code point.</summary>
    public static class GlazeIconGlyphs
    {
        /// <summary>The icon's glyph, as the text of a label in the icon font.</summary>
        public static string Of(GlazeIcon icon) => icon switch
        {
            GlazeIcon.NotStarted => "\uE836", // radio_button_unchecked
            GlazeIcon.Starting => "\uEA5B", // hourglass_top
            GlazeIcon.Working => "\uE9D0", // progress_activity
            GlazeIcon.CheckingItsWork => "\uF0C5", // fact_check
            GlazeIcon.WaitingForYou => "\uE769", // front_hand
            GlazeIcon.FinishedThisRound => "\uE153", // flag
            GlazeIcon.ChecksFailed => "\uE85F", // assignment_late
            GlazeIcon.CouldNotFinish => "\uE5C9", // cancel
            GlazeIcon.Stopped => "\uEF71", // stop_circle
            GlazeIcon.CantTellYet => "\uE887", // help
            GlazeIcon.LastKnown => "\uE28E", // history
            GlazeIcon.Practice => "\uEA4B", // science
            GlazeIcon.Recording => "\uE02C", // movie
            GlazeIcon.Approve => "\uE5CA", // check
            GlazeIcon.Deny => "\uE033", // block
            GlazeIcon.Stop => "\uEF71", // stop_circle
            GlazeIcon.TellIt => "\uE0B7", // chat
            GlazeIcon.SendAnswer => "\uE163", // send
            GlazeIcon.HoldToTalk => "\uE029", // mic
            GlazeIcon.Type => "\uE312", // keyboard
            GlazeIcon.StartBuilding => "\uE037", // play_arrow
            GlazeIcon.StartOver => "\uF053", // restart_alt
            GlazeIcon.Refresh => "\uE5D5", // refresh
            GlazeIcon.Change => "\uE150", // edit
            GlazeIcon.ConnectProjects => "\uE157", // link
            GlazeIcon.CreateProject => "\uE145", // add
            GlazeIcon.AddTask => "\uF23A", // add_task
            GlazeIcon.OpenNow => "\uF1CE", // open_in_full
            GlazeIcon.KeepCreating => "\uE745", // edit_note
            GlazeIcon.NotNow => "\uE192", // schedule
            GlazeIcon.Close => "\uE14C", // close
            GlazeIcon.Back => "\uE5C4", // arrow_back
            GlazeIcon.Next => "\uE5C8", // arrow_forward
            GlazeIcon.Move => "\uF71E", // drag_pan
            GlazeIcon.ResetPosition => "\uE3B4", // center_focus_strong
            GlazeIcon.ShowAll => "\uE417", // visibility
            GlazeIcon.Settings => "\uE8B8", // settings
            GlazeIcon.UsageLeft => "\uE9E4", // speed
            GlazeIcon.Locked => "\uE88D", // lock
            GlazeIcon.CodeFile => "\uE86F", // code
            GlazeIcon.DatabaseFile => "\uF20E", // database
            GlazeIcon.DataFile => "\uEAD3", // data_object
            GlazeIcon.TextFile => "\uE873", // description
            GlazeIcon.ImageFile => "\uE251", // image
            GlazeIcon.ScriptFile => "\uEB8E", // terminal
            GlazeIcon.PackageFile => "\uF720", // deployed_code
            GlazeIcon.Folder => "\uE2C7", // folder
            GlazeIcon.OpensMore => "\uE409", // chevron_right
            GlazeIcon.WritingDown => "\uF8EC", // transcribe
            _ => throw new ArgumentOutOfRangeException(nameof(icon), icon, "Unhandled icon."),
        };

        /// <summary>Every glyph the font holds, in code point order: what the atlas is built from.</summary>
        public const string All = "\uE029\uE02C\uE033\uE037\uE0B7\uE145\uE14C\uE150\uE153\uE157\uE163\uE192\uE251\uE28E\uE2C7\uE312\uE3B4\uE409\uE417\uE5C4\uE5C8\uE5C9\uE5CA\uE5D5\uE745\uE769\uE836\uE85F\uE86F\uE873\uE887\uE88D\uE8B8\uE9D0\uE9E4\uEA4B\uEA5B\uEAD3\uEB8E\uEF71\uF053\uF0C5\uF1CE\uF20E\uF23A\uF71E\uF720\uF8EC";
    }
}
