// Generated by apps/xr/tools/glaze_icons.py from Material Symbols Rounded 2.972 (FILL 1, wght 500, GRAD 0, opsz 24).
// Do not edit: change the script's list and run it again (docs/internal/runbooks/XR_DEVELOPMENT.md).
#nullable enable
using System;
using Halcyonic.Client;

namespace Halcyonic.XR.UI
{
    /// <summary>The glyph of every icon in the Glaze icon font: the only code that knows a code point.</summary>
    public static class GlazeIconGlyphs
    {
        /// <summary>The icon's glyph, as the text of a label in the icon font.</summary>
        public static string Of(GlazeIcon icon) => icon switch
        {
            GlazeIcon.NotStarted => "\uE836", // radio_button_unchecked
            GlazeIcon.Starting => "\uEA5B", // hourglass_top
            GlazeIcon.Working => "\uE9D0", // progress_activity
            GlazeIcon.CheckingItsWork => "\uF0C5", // fact_check
            GlazeIcon.WaitingForYou => "\uE769", // front_hand
            GlazeIcon.FinishedThisRound => "\uE153", // flag
            GlazeIcon.ChecksFailed => "\uE85F", // assignment_late
            GlazeIcon.CouldNotFinish => "\uE5C9", // cancel
            GlazeIcon.Stopped => "\uEF71", // stop_circle
            GlazeIcon.CantTellYet => "\uE887", // help
            GlazeIcon.LastKnown => "\uE28E", // history
            GlazeIcon.Practice => "\uEA4B", // science
            GlazeIcon.Recording => "\uE02C", // movie
            _ => throw new ArgumentOutOfRangeException(nameof(icon), icon, "Unhandled icon."),
        };

        /// <summary>Every glyph the font holds, in code point order: what the atlas is built from.</summary>
        public const string All = "\uE02C\uE153\uE28E\uE5C9\uE769\uE836\uE85F\uE887\uE9D0\uEA4B\uEA5B\uEF71\uF0C5";
    }
}
