#!/usr/bin/env python3
"""Makes the Glaze icon font and its code point table from Material Symbols Rounded.

ADR 0023: one icon set, Material Symbols Rounded (Apache-2.0), filled, weight 500, grade 0, optical
size 24, as a static TextMeshPro SDF atlas of only the glyphs the interface uses, named by meaning
in the client core (GlazeIcon). This script keeps only those glyphs of Google's variable font, pins
it to that style, and writes:

- Assets/Halcyonic/UI/Icons/MaterialSymbolsRounded-Glaze.ttf, the font the atlas is built from,
  renamed and described as changed, as the Apache License asks of a changed file;
- Assets/Halcyonic/UI/Primitives/GlazeIconGlyphs.cs, the only code that knows a code point.

Run it with the variable font from https://github.com/google/material-design-icons (variablefont/),
then build the atlas in Unity (Halcyonic > Build the Icon Atlas):

    python3 apps/xr/tools/glaze_icons.py "MaterialSymbolsRounded[FILL,GRAD,opsz,wght].ttf"

It needs fontTools; 4.65.0 makes the committed font byte for byte. Only its output and the font's
LICENSE are committed.
"""

import argparse
import hashlib
import re
import sys
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

XR = Path(__file__).resolve().parents[1]
ENUM_SOURCE = XR / "Packages/com.halcyonic.client/Runtime/StateLanguage.cs"
FONT_OUT = XR / "Assets/Halcyonic/UI/Icons/MaterialSymbolsRounded-Glaze.ttf"
TABLE_OUT = XR / "Assets/Halcyonic/UI/Primitives/GlazeIconGlyphs.cs"

UPSTREAM_FAMILY = "Material Symbols Rounded"
FAMILY = "Material Symbols Rounded Glaze"
POSTSCRIPT = "MaterialSymbolsRounded-Glaze"

# The Glaze style: filled, weight 500, grade 0, optical size 24.
STYLE = {"FILL": 1, "wght": 500, "GRAD": 0, "opsz": 24}

# Every GlazeIcon by meaning, and the Material Symbols glyph that shows it, from the approved spec's
# table "Every meaning has one icon". No two states share a glyph.
ICONS = {
    "NotStarted": "radio_button_unchecked",
    "Starting": "hourglass_top",
    "Working": "progress_activity",
    "CheckingItsWork": "fact_check",
    "WaitingForYou": "front_hand",
    "FinishedThisRound": "flag",
    "ChecksFailed": "assignment_late",
    "CouldNotFinish": "cancel",
    "Stopped": "stop_circle",
    "CantTellYet": "help",
    "LastKnown": "history",
    "Practice": "science",
    "Recording": "movie",
}


def fail(message):
    sys.exit("glaze_icons: " + message)


def enum_members(source):
    """The members of the client core's GlazeIcon enum, in order."""
    match = re.search(r"public enum GlazeIcon\s*\{(.*?)\}", source, re.S)
    if match is None:
        fail(f"no GlazeIcon enum in {ENUM_SOURCE}")
    body = re.sub(r"//[^\n]*", "", match.group(1))
    return [member.strip() for member in body.split(",") if member.strip()]


def name_of(font, name_id):
    record = font["name"].getName(name_id, 3, 1, 0x409)
    return record.toUnicode() if record is not None else ""


def code_points(font, glyphs):
    """Each glyph's code point: the lowest the font maps to it, since some glyphs have old aliases."""
    by_glyph = {}
    for code_point, glyph in font.getBestCmap().items():
        by_glyph.setdefault(glyph, []).append(code_point)
    found = {}
    for glyph in glyphs:
        if glyph not in by_glyph:
            fail(f"{glyph} is not in the font")
        found[glyph] = min(by_glyph[glyph])
    return found


def rename(font, upstream_version, glyph_count):
    """Names the font as changed, so it is never taken for Google's own."""
    name = font["name"]
    name.names = [record for record in name.names if record.platformID == 3 and record.nameID in (0, 1, 2, 3, 4, 5, 6)]
    style = " ".join(f"{axis} {value}" for axis, value in STYLE.items())
    names = {
        1: FAMILY,
        2: "Regular",
        3: f"{upstream_version};HALCYONIC;{POSTSCRIPT}",
        4: FAMILY,
        5: f"Version {upstream_version}; Glaze subset",
        6: POSTSCRIPT,
        10: f"{UPSTREAM_FAMILY} {upstream_version} by Google, changed for Halcyonic: pinned to {style} "
        f"and cut to the {glyph_count} glyphs its interface uses.",
        13: "Licensed under the Apache License, Version 2.0.",
        14: "https://www.apache.org/licenses/LICENSE-2.0",
    }
    for name_id, text in names.items():
        name.setName(text, name_id, 3, 1, 0x409)


def table(members, glyph_of, code_point_of, upstream_version):
    style = ", ".join(f"{axis} {value}" for axis, value in STYLE.items())
    lines = [
        f"// Generated by apps/xr/tools/glaze_icons.py from {UPSTREAM_FAMILY} {upstream_version} ({style}).",
        "// Do not edit: change the script's list and run it again (docs/internal/runbooks/XR_DEVELOPMENT.md).",
        "#nullable enable",
        "using System;",
        "using Halcyonic.Client;",
        "",
        "namespace Halcyonic.XR.UI",
        "{",
        "    /// <summary>The glyph of every icon in the Glaze icon font: the only code that knows a code point.</summary>",
        "    public static class GlazeIconGlyphs",
        "    {",
        "        /// <summary>The icon's glyph, as the text of a label in the icon font.</summary>",
        "        public static string Of(GlazeIcon icon) => icon switch",
        "        {",
    ]
    for member in members:
        glyph = glyph_of[member]
        lines.append(f'            GlazeIcon.{member} => "\\u{code_point_of[glyph]:04X}", // {glyph}')
    lines += [
        '            _ => throw new ArgumentOutOfRangeException(nameof(icon), icon, "Unhandled icon."),',
        "        };",
        "",
        "        /// <summary>Every glyph the font holds, in code point order: what the atlas is built from.</summary>",
        '        public const string All = "' + "".join(f"\\u{code_point:04X}" for code_point in sorted(set(code_point_of.values()))) + '";',
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("variable_font", type=Path, help="MaterialSymbolsRounded[FILL,GRAD,opsz,wght].ttf")
    arguments = parser.parse_args()

    members = enum_members(ENUM_SOURCE.read_text(encoding="utf-8"))
    if set(members) != set(ICONS):
        fail(f"GlazeIcon and the list differ: only in GlazeIcon {sorted(set(members) - set(ICONS))}, "
             f"only in the list {sorted(set(ICONS) - set(members))}")

    source = arguments.variable_font.read_bytes()
    font = TTFont(arguments.variable_font, recalcTimestamp=False)
    if name_of(font, 1) != UPSTREAM_FAMILY:
        fail(f"expected {UPSTREAM_FAMILY}, found {name_of(font, 1)!r}")
    axes = {axis.axisTag for axis in font["fvar"].axes}
    if axes != set(STYLE):
        fail(f"expected the axes {sorted(STYLE)}, found {sorted(axes)}")
    upstream_version = name_of(font, 5).removeprefix("Version ")

    glyphs = sorted(set(ICONS.values()))
    code_point_of = code_points(font, glyphs)
    if any(code_point > 0xFFFF for code_point in code_point_of.values()):
        fail("a glyph lies outside the Basic Multilingual Plane, which the table's escapes do not reach")

    # Cut first, then pin: pinning only the kept glyphs takes moments, not minutes.
    options = subset.Options()
    options.layout_features = []
    options.hinting = False
    options.glyph_names = True
    options.notdef_outline = True
    options.recalc_timestamp = False
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=sorted(code_point_of.values()))
    subsetter.subset(font)
    pinned = instancer.instantiateVariableFont(font, STYLE)
    pinned.recalcTimestamp = False
    # Nothing left to substitute and no axes left to describe.
    for tag in ("GSUB", "STAT"):
        if tag in pinned:
            del pinned[tag]
    rename(pinned, upstream_version, len(glyphs))
    FONT_OUT.parent.mkdir(parents=True, exist_ok=True)
    pinned.save(FONT_OUT)

    glyph_of = {member: ICONS[member] for member in members}
    TABLE_OUT.write_text(table(members, glyph_of, code_point_of, upstream_version), encoding="utf-8")

    made = FONT_OUT.read_bytes()
    print(f"{UPSTREAM_FAMILY} {upstream_version}, {len(source):,} bytes, sha256 {hashlib.sha256(source).hexdigest()}")
    print(f"{FONT_OUT.relative_to(XR)}: {len(glyphs)} glyphs, {len(made):,} bytes, sha256 {hashlib.sha256(made).hexdigest()}")
    print(f"{TABLE_OUT.relative_to(XR)}: {len(members)} icons")


if __name__ == "__main__":
    main()
